### ISSUE TITLE
Huckle-Patch Pre-Deployment Checklist

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1225]
**Checklist Items:**
- [] Any pre-release scripts/updates to JS or Database, etc..
- [] Tickets in "Ready for Deploy" Have been verified as implemented, non regressed "Deployment Ready Verified" 

- [] Tickets in Ready for Deploy have been approved by Project Leads (Sign Off)
              
**Deployment Sign off:**
             - [] Rickie Thornley (QA)
             - [] @sanjuroj 
             - [] @jennyhavah
