### ISSUE TITLE
Indicator Performance Tracking Table (IPTT): Export to Excel

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#123]
## Accessing exports

Please add placeholder buttons that look something like this. (Paul has a ticket to review and style these buttons -- #344)
![image](https://user-images.githubusercontent.com/33670923/40453355-cdb2d0e0-5e99-11e8-8e55-a77b3bdcc2b4.png)

![image](https://user-images.githubusercontent.com/33670923/40453363-d289d50a-5e99-11e8-924c-07c969c074ec.png)

## Export to Excel
Formatting can be minimal, but the following should be true:
- [ ] 1. All report headers, columns, and rows are visible.
- [ ] 2. Text is set to wrap inside columns, so that all contents are visible.
- [ ] 3. Left- and right- alignments are consistent with the web version.
- [ ] 4. Nothing from the filter panel is exported, nor are the gear or dot-dot-dot icons.
- [ ] 5. The report title and program names are large.
- [ ] 6. The header row is differentiated in some way -- bold, shaded, etc.
