### ISSUE TITLE
RF builder: Select a template with predefined levels

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1245]
# Stories
1. As a program team meeting PM@MC minimum standards, it's easy to get started building my framework using the level labeling conventions Mercy Corps recommends.
2. As a program team reporting to a major donor, I can easily apply the results framework level labels my donor requires.
3. As a country or regional manager or M&E advisor, I can easily enforce consistent program logic terminology across the programs I manage / advise.

# Acceptance criteria

## Empty state before a template is applied for the first time

**Preconditions:**
1. User is assigned High level permissions for the program. (See #1252 for in-depth coverage of roles and permissions.)

2. User accessed the RF builder from the program page as described in #1246.

3. A template has _never been applied_ to this program. Meaning, even though you see the default template selected in the menu, nobody has yet clicked "Apply" to confirm that the default is the one they want. 

The goal of the empty state is to focus users' attention on the template menu and make sure they _proactively and intentionally select a template_ before they jump into saving levels.

![image](https://user-images.githubusercontent.com/33670923/54950828-6a62d600-4eff-11e9-9f62-0aa15007f506.png)

- [x] 1. The title of the page is: [Program name]: Results framework

- [x] 2. There is a prominent representation of a diagram on the page to visually convey the concept of hierarchy -- what you're getting into here. 

- [x] 3. There are instructions in large text, with the first sentence red and bold: **Choose your results framework template carefully!** Once you begin building your framework, it will not be possible to change templates without first deleting all saved levels.

- [x] 4. To the left of the warning is the template selection area, with an illustration of the levels you're using in that template.

     - [x] 4.1. The title of the FN is "Results framework template"

     - [x] 4.2. Below the title is a single-select menu of templates that includes all of the options defined in #1247.

          - [x] 4.2.1. _Mercy Corps_ is the default selection.

          - [x] 4.2.2. There is no "null" option such as ------. There _must_ be a template selected.

     - [x] 4.3. Under the template menu is a preview of the levels included in the template, visually expressed as a hierarchy.

     - [ ] 4.4. Clicking the **Apply** button produces the following view:
          ![image](https://user-images.githubusercontent.com/33670923/54950854-7d75a600-4eff-11e9-93af-c7b2914655ce.png)

          - [x] 4.4.1. You see the first top-level form in its empty state. For the _Mercy Corps_ template, this means you'd see a Goal form.

          - [x] 4.4.2. Template instructional text goes away, moved into a tool-tip accessed from a question mark icon in the upper right corner, like so:

          ![image](https://user-images.githubusercontent.com/33670923/54951284-7e5b0780-4f00-11e9-9c19-180506f150e5.png)

## Rules about changing templates

As soon as you apply any template for the first time, _you do not return to the original empty state_ with the giant diagram icon, etc. The original instructional text is now a tool-tip. Going forward, here are the rules around changing templates:

### When there are no saved levels

![image](https://user-images.githubusercontent.com/33670923/54951742-a139eb80-4f01-11e9-824e-d8aa1383dd53.png)

- [x] 1. There is no longer an "Apply" button. Until I've saved my first level, I can change templates by selecting a different option from the menu, which causes the following to happen:
     - [x] 1.1. The preview of levels refreshes to display the one you just selected.
     - [x] 1.2. The top level form updates to use the correct level name in all relevant locations:
          - [x] 1.2.1. Level title in the upper left corner
          - [x] 1.2.1. Indicator selection menu
          - [ ] 1.2.1. **Save and add another [Level]** button
          - [x] 1.2.1. **Save and link a [Level]** button

### When there is at least one saved level

![image](https://user-images.githubusercontent.com/33670923/54950916-a39b4600-4eff-11e9-935e-e6ebb4666a80.png)

- [x] 1. I cannot change templates. The template menu is inactive. (I can open it to see what's in there, but I cannot select anything.)

     - [ ] ~1.1. Visual detail: Note that in my mockups, in addition to the form object itself being active/inactive, I use our teal active color behind the menu when it's editable and gray when it can no longer be edited. This is just to give extra "call to action" emphasis in a somewhat busy view people have just begun to absorb.~ Not a requirement.

- [x] 2. **The tool-tip messaging changes to the following:** The results framework template cannot be changed after levels are saved. To change templates, all saved levels first must be deleted. A level can be deleted when it has no sub-levels and no linked indicators.

![image](https://user-images.githubusercontent.com/33670923/54951440-e4478f00-4f00-11e9-9b1e-ceb43820f4fc.png)

- [x] 3. If I delete **_all_** of my saved levels, the page returns to the state depicted below, _maintaining the currently selected template_, and the template menu active again, so that I can switch if I want to. (The mockup below should not be interpreted to mean that we revert back to _Mercy Corps_ as the default template. We should preserve the user's most recent selection.)

![image](https://user-images.githubusercontent.com/33670923/56072405-44389500-5d4b-11e9-8a08-f19ef5e5c97f.png)

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by axoplasm** [comment]
> 4.2.1. Mercy Corps is the default selection.

This currently reads “Mercy Corps Standard” which conforms to #1247 

![image](https://user-images.githubusercontent.com/169060/58494291-a138b080-8129-11e9-8354-db48ec395988.png)

**Comment by axoplasm** [comment]
> 1.2.1. Save and add another [Level] button

There is no “save and add another [level]” button for the top level in the hierarchy

![image](https://user-images.githubusercontent.com/169060/58494540-258b3380-812a-11e9-842c-3e909ddb7542.png)

**Comment by axoplasm** [comment]
> 1.2.1. Save and link a [Level] button

This text has been shorted to “Save and link” (see screenshot above)

**Comment by jennyhavah** [comment]
@sanjuroj Can we list the templates in alphabetical order? Here's what I see now:

![image](https://user-images.githubusercontent.com/33670923/59546175-f6bcdd80-8edd-11e9-9127-057f6aa5e72a.png)

**Comment by jennyhavah** [comment]
@sanjuroj How easy or difficult would it be to set the following rules, regarding the page title?

![image](https://user-images.githubusercontent.com/33670923/59546270-2cae9180-8edf-11e9-866c-0288b78b2106.png)

1. IF there are no indicators associated with the program, then the program name is NOT linked to the program page.

2. IF there is at least one indicator associated with the program, then the program name IS linked to the program page.

(We've been doing what we can to avoid sending people to an empty program page with no indicators, because it's super busy without any obvious call to action...)

**Comment by sanjuroj** [comment]
@jennyhavah All the stuff you mention is easy.  How would you like the non-linked title to look?  Like regular text or like a disabled link?

**Comment by jennyhavah** [comment]
@sanjuroj I would like it to still look like a page header, just not linked. 

I'm not sure which style this would be, but visually, I'd like the text to still be bold, but instead of the blue link color, we use the same shade of gray we use for the page title in our IPTT. (Illustration is just for color purposes -- the text looks bigger than what we're currently using on the RF builder page.)

![image](https://user-images.githubusercontent.com/33670923/59621631-8f24af00-90e4-11e9-8b2e-db7661c0435f.png)

**Comment by sanjuroj** [comment]
@jennyhavah These changes should all be in the codebase now.

**Comment by jennyhavah** [comment]
Just encountered this error immediately after saving my first RF Goal and adding my first indicator to it. I clicked the program link in the header and got this:

![image](https://user-images.githubusercontent.com/33670923/59806643-eb84fb80-92a9-11e9-828c-0a4f79114503.png)

**Comment by jennyhavah** [comment]
@sanjuroj Just attempted to replicate it twice using the same steps, and it was fine. Hopefully just a Jenkins glitch or some such.

**Comment by jennyhavah** [comment]
PASSED. All acceptance criteria and requests in the comment have been met.
