### ISSUE TITLE
RF builder: Add / edit a level

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1251]
**Affected by:** #1282 -- prompts for rationales upon saving, when certain conditions are met. Shouldn't block this ticket, but something to keep in mind. 

# Story
As someone responsible for defining program logic, I can communicate the logic to TolaActivity, so that the system can organize indicators and results accordingly.

# Acceptance criteria

**Precondition:**  I am about to edit an RF level form at any level. This can happen in one of two ways:
1. I click _Edit_ on a saved level.
2. I click _Save and add another_ on a new level.

_Keep in mind that there is no other way to open an RF level form. Clicking on accordion arrows or RF level text **opens the RF level TIER, not the RF level FORM.**_

## Add or edit level: Form components

![image](https://user-images.githubusercontent.com/33670923/54553186-e5137a80-496e-11e9-8395-d51d6cd6fee7.png)

- [x] 1. **Level followed by number**
     - [x] 1.1. Exception: The top level (i.e. Goal in if you're using the Mercy Corps template) is NOT followed by a number. This exception is explained in ticket 1253. 

**Note:** Auto-numbering system is covered in #1253.

- [x] 2. **Level text box**
     - [x] 2.1. The Level text box is a _required field_. 

     - [x] 2.2. Until you type something in the text box, the following elements remain _**inactive**_:
          - [x] 2.1.1. Assumptions text area field
          - [x] 2.1.2. _Save [RFTier] and add indicators_ button
          - [x] 2.1.3. All megabuttons in the Save row, except for Cancel <P>

     ![image](https://user-images.githubusercontent.com/33670923/59527845-8e480f00-8e91-11e9-95dc-2e26655da2a1.png)

     - [x] 2.2. If I type something into the Level text box and later delete the text, there is some combination of front- and back-end validation to prohibit you from submitting the form. 

          - [x] 2.2.1. On the front end, I propose we re-disable the three megabuttons and give the text box the standard "Please complete this field" treatment with red outline. (To emphasize, this warning treatment should only happen if you delete some text that was already entered -- not when you first open the form, before you've done anything.) <P>
     
- [x] 3. **Assumptions text box:** This is NOT a required field.

- [x] 4. **Save [RFtier] and add indicators button:** It is NOT required that you add indicators prior to saving. Because of the complexity around adding indicators, I broke out this area into its own ticket. See #1275.

     - [x] 4.1. The format of the button is "Save [RFtier] and add indicators". Please use Title Case for the RF Tier -- for example, "Save Intermediate Objective and add indicators"

     - [x] 4.2. Styling-wise, I'd like this button to have more visual weight than it normally does, so that it holds its own against the megabuttons -- for example, in the mockup I used the same font size/boldness as the megabuttons, with the icon scaled up to match.

     - [x] 4.3. If you DO choose to click the button, the Indicator add / edit / delete box appears, like so:

     ![image](https://user-images.githubusercontent.com/33670923/59527983-ee3eb580-8e91-11e9-9dd9-e2afb690d92f.png)

## Saving

- [x] 1. **Save and close**

     - [x] 1.1. System saves form entries.

     - [x] 1.2. Form goes away, replaced by the saved level. All details about saved levels are covered in ticket #1254 -- but here are some examples of what saved levels look like:
     ![image](https://user-images.githubusercontent.com/33670923/53915302-810ac100-4014-11e9-9a16-289db643289b.png)
----
- [x] 2. **Save and add another [Sibling Level]**

     - [x] 2.1. System saves form entries.

     - [x] 2.2. Form goes away, replaced by the saved level. 

     - [x] 2.3. A new form _of the SIBLING level_ appears immediately below the level form in which you clicked the button. 
![image](https://user-images.githubusercontent.com/33670923/54552486-6a962b00-496d-11e9-80b7-249422583847.png)  

          - [x] 2.3.1. This is true even if the level is in the middle of a list of siblings. (In other words, we don't automatically add a new sibling level to the end of the list and make you reorder it later. We give you a way to put it where you want it from the start.) <P>

- [x] 2.4. Exception: This button **does not appear at all** for the highest level in the RF. For example, here's a form for the highest level in the Mercy Corps RF template, called "Goal". Note that there is no "Add another Goal" button:
          ![image](https://user-images.githubusercontent.com/33670923/54552621-c3fe5a00-496d-11e9-9575-979c95dbf534.png)

----
- [x] 3. **Save and link [Child Level]**

     - [x] 3.1. System saves form entries.

     - [x] 3.2. Form goes away, replaced by the saved level. 

     - [x] 3.3. A new form _of the CHILD level_ appears immediately below the level form in which you clicked the button, **indented enough to communicate nesting**

          ![image](https://user-images.githubusercontent.com/33670923/54552771-193a6b80-496e-11e9-9f40-88f1254a20b1.png)

     - [x] 3.4. Exception: This button **does not appear at all** for the lowest level in the RF. For example, here's a form for the lowest level in the Mercy Corps RF template, called "Activity". Note that there is no "Save and link [no such thing]" button. 
     
     ![image](https://user-images.githubusercontent.com/33670923/54553483-839fdb80-496f-11e9-864f-e68df5479e93.png)

## Preventing data loss

**Note:** The phrase "editing an RF level" refers to (a)Entering or modifying RF level or Assumptions text and (b) Rearranging the order of linked indicators. It does NOT refer to editing an Indicator's settings.

- [x] 1. General rule: I CANNOT close an RF level form, at any time, by clicking outside the area. Following are the ways in which I can back out of a form.

### Before editing an RF level

- [x] 1. Clicking _Cancel_ closes the form, leaving any parents/siblings above or below intact.

     - [x] ~1.1. Exception: If I've never saved the topmost level, start editing it and click Cancel, the form does not disappear -- it just clears, returning it to its empty state.~ [This isn't meaningful since nothing has been changed yet]

- [x] 2. While I have one RF level form open, I can click the _Edit_ button on a different RF level. 

     - [x] 2.1. Because I haven't made any changes, I don't get any prompts. 

     - [x] 2.2. The new RF level form pops open and the one I had open previously, **_automatically closes_** I _cannot have multiple RF level forms open at the same time._

### After editing an RF level

Note: This criteria was updated June 19 to remove excessive prompt.

- [x] 1. IF (and only if) I make some edits to **text** or **indicator order** in an RF form and click _Cancel_ on that _exact same form_:

     - [x] 1. Changes to text or indicator order are not saved. _(Note: Changes to indicators themselves -- how many there are, edits made to them, are not expected to be undone. Once you save indicator changes, they're saved, period.)_

     - [x] 2. The form closes, leaving any parents/siblings above or below intact.

- [x] 2. If I've edited an RF level and click _Edit_ on a DIFFERENT RF level, I get a yellow warning  prompt positioned in the lower left corner of the screen: Changes to this [RF tier] will not be saved. Are you sure you want to continue?

     ![image](https://user-images.githubusercontent.com/33670923/55255550-2c73f380-5218-11e9-9d77-9a72d2acd4d8.png)

     - [x] 2.1. In a results framework with lots of levels, you could potentially not see the warning prompt if it appears above or below the fold. Ideally, I am auto-scrolled to where the original form (and warning) are located.

     - [x] 2.2. If I dismiss the warning by clicking _Cancel_ or the "X" button in the upper right corner of the prompt, the prompt closes, leaving the current RF level form open and intact. The other RF level form I attempted to open by clicking its _Edit_ button does NOT open.

     - [x] 2.2. _Clicking OK_ does the following:

          - [x] 2.2.1. Closes the form, leaving any parents/siblings above or below intact. 

          - [x] 2.2.2. Changes are NOT saved.

          - [x] 2.2.3. The other RF level form whose _Edit_ button I previously clicked, opens. I am auto-scrolled to that RF form so that if it happens to be above or below the fold, I can see that it is now open and available to edit.
		
## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by sanjuroj** [comment]
@jennyhavah I wanted to confirm some changes in spec that I remember talking about but apparently not noting here.  In the section **Before editing an RF level**, I think we said that users would be able to click on the edit button to open other levels, but that the save buttons would be deactivated until the first one that was activate was disposed of in some way.

**Comment by jennyhavah** [comment]
@sanjuroj See 2.2. In a case where you have not yet made any edits to the _**first**_ RF level, my understanding was that it automatically closes when you click "Edit" on a different RF level. No reason why the buttons for the second RF level need to be disabled -- beyond our usual rules about the buttons being inactive until required fields are complete.

**Comment by sanjuroj** [comment]
There are still two potentially outstanding issues:
- The confirmation popup that appears when you try to cancel edits ("After editing an RF level" item #1) is in the lower left of the _viewport_, not the level box.  
- When you are editing a card and hit the edit button of another card, you are automatically scrolled to so the first card is at the top of the screen, even if the card is already in the viewport.  It might be nice to scroll only if the card is outside of the viewport.

**Comment by jennyhavah** [comment]
@sanjuroj Regarding this criteria:

![image](https://user-images.githubusercontent.com/33670923/59734088-f76ab200-9204-11e9-97e2-90a1d1db295e.png)

In the mockup, I intentionally used the yellow warning style, because "Cancelling" generally means you're trying to back out of something / recover something -- as opposed to a more destructive action like deleting something that is non-recoverable.

Right now I'm seeing the red warning style:

![image](https://user-images.githubusercontent.com/33670923/59734175-37ca3000-9205-11e9-9810-40a18b839bad.png)

Any objections to using the yellow warning style instead?

**Comment by jennyhavah** [comment]
> There are still two potentially outstanding issues:
> 
> The confirmation popup that appears when you try to cancel edits ("After editing an RF level" item #1) is in the lower left of the viewport, not the level box.

This is fine.

> When you are editing a card and hit the edit button of another card, you are automatically scrolled to so the first card is at the top of the screen, even if the card is already in the viewport. It might be nice to scroll only if the card is outside of the viewport.

I like the current behavior. Even if the card is visible, there's something nice about it moving into a more prominent position -- just the movement itself is helpful system feedback.

**Comment by sanjuroj** [comment]
Nope, no objections to switching to yellow.

**Comment by jennyhavah** [comment]
@sanjuroj As per our conversation just now, please see updates to the first two scenarios under "Preventing data loss."

**Comment by jennyhavah** [comment]
PASSED. All acceptance criteria met!
