### ISSUE TITLE
RF builder: Saved levels

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1254]
# Stories
1. I can view the program logic that drives our indicator plan in a compact and accessible format.
2. I can easily see how specific program indicators contribute to a program's intended impact.
3. As someone with High permission, I can open up the RF level to edit it.
4. As someone with High permission, I can delete a level.

**Note:** There are references to High permissions in this ticket. For details on roles and permissions, see #1252.

# Acceptance criteria

![image](https://user-images.githubusercontent.com/33670923/53927108-985ca500-403a-11e9-91ad-ca40c039d2c2.png)

- [x] 0. By default, when you land on the RF builder page, _**all tiers are expanded to reveal any sub-tiers.**_

- [x] 1. If a level has sub-levels, I can expand and collapse it by:

     - [x] 1.1. Clicking on the expando/contracto **caret** on the left edge.

     - [x] 1.2. Clicking the **text** of the level. _To emphasize, clicking on the text **does NOT open the RF level form**. It behaves exactly as if you'd clicked the expando/contracto caret._

- [x] 2. The saved level includes:

     - [x] 2.1. The level followed by the number and a colon -- all in bold text. (Exception: The top level does not include a number -- see #1253 for details on numbering.) 

     - [x] 2.2. The text of the level in plain text.

- [x] 3. _If I have High permission,_ I see the **Edit** button in the upper right corner. 

     - [x] 3.1. Clicking **Edit** opens up the level form. (See #1251 for form details.) <P>

- [x] 4. If at least one indicator is linked to the level, I see a link "# indicators" 

     - [x] 4.1. Make sure singulars and plurals are handled appropriately in the 3 supported languages. (1 indicator, 2 indicators, etc.)

     - [x] 4.2. Clicking the link opens a single-select menu that gives you options for viewing a filtered time period based IPTT, set to show all time periods. See #1298 Section 3 regarding changes to the Indicators filter to incorporate RF levels. There may be relevant "hooks" here.
![image](https://user-images.githubusercontent.com/33670923/55349322-40189780-546e-11e9-935f-6e26b374e8c2.png) 

          - [x] 4.2.1. The title of the menu is: Track indicator performance 

          - [x] 4.2.2. The first option is "All indicators linked to [RF level][RF level number] and sub-levels. _This option should only appear if the indicator actually has sub-levels._ Clicking it takes you to the **time period based** (not target vs actuals) IPTT filtered on these indicators, showing all available data.

          - [x] 4.2.3. The second option is "All indicators linked to [RF level][RF level number]. licking it takes you to the time period based IPTT filtered on these indicators.

          - [x] 4.2.4. Next come the individual indicators linked to the RF level, in numeric order. Clicking any of these takes you to the IPTT filtered on that single indicator.

- [x] 5. The **Delete** button only appears when the following conditions are met:

     - [x] 5.1. I have High permission.

     - [x] 5.2. The level contains no sub-levels.

     - [x] ~5.3. The level is not the top level -- Goal in the case of the MC template. (That level cannot ever be deleted, only edited.)~ [Note: this conflicts with #1245 Item 3.  Leaving it here just as a reminder in case we remember why we wanted this restriction.]

     - [x] 5.4. There are no indicators linked to the level.

     - [x] 5.5. _**So what happens when I click Delete?**_ Because it is not possible to delete an RF level with sub-levels or that have indicators linked to them, there is no need for a rationale prompt, as per the rules described in #1282 . However, we DO need to warn the user that the action cannot be undone. 

          - [x] 5.5.1. Let's use a standard PNotify red warning prompt with the following message:

          Warning
          This action cannot be undone.
          Are you sure you want to delete [RF tier][RFLevelNumber]?

          For example: Are you sure you want to delete Activity 1.1.3?

          - [x] 5.5.2. The warning should be positioned in the lower left corner of the screen.

          ![image](https://user-images.githubusercontent.com/33670923/55653270-d6b4c380-57a2-11e9-9c9b-ec7d49e853de.png)

          - [x] 5.5.3. If I click "Cancel" or the "X" button, the PNotify warning closes and the RF level is preserved.

          - [x] 5.5.4. If I click "OK", the RF level is deleted, and a temporary, self-dismissing growl of success appears in the lower left corner of the screen. It says:

               Success
               [RF tier][RFLevelNumber] was deleted.
          
               ![image](https://user-images.githubusercontent.com/33670923/57323259-555e9280-70ba-11e9-9ce3-41372b6e1b2c.png)

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by sanjuroj** [comment]
@jennyhavah Question related to 5.3 above specifying that there should be no delete button on the top tier level.  According to the warning messages on #1245, we want to allow them to change templates if they delete everything.  The easiest way to accomplish this is to enable deletion of the top tier level and immediately recreate that level as a blank form.  I've implemented this in the current codebase if you wan to see what it feels like.

**Comment by sanjuroj** [comment]
Leaving a note to document some changes in the spec:
- We're going to do a simple list for the indicator popover, rather than the select/filter.  We can gather data on how many indicators get assigned to levels and adjust the selection machinery based on the data.
- The indicator list in the popover is going to start with the indicator ontology, which avoids repetitious text and creates visual distinction between rows.

**Comment by sanjuroj** [comment]
@axoplasm I think it's mainly the positioning of the delete pnotify msgs that need some work.

**Comment by axoplasm** [comment]
I can't do much with this DOM. If I push it into a different container it may fall below the fold. I gave it a little space away from the edge of the viewport

![image](https://user-images.githubusercontent.com/169060/59123970-57af4900-8913-11e9-9f17-8bf561ee2fdc.png)

**Comment by jennyhavah** [comment]
@axoplasm Under certain conditions, the # indicators link is indented instead of being right-aligned with the Edit button. Best I can tell, it has to do with whether or not there are sub-levels.

![image](https://user-images.githubusercontent.com/33670923/59242494-9ddd0480-8bc0-11e9-9e98-f926f9e6fb16.png)

**Comment by jennyhavah** [comment]
@sanjuroj Throwing this to you because Paul is out.

Very minor text nit pick: Can you remove the redundant word "successfully" from the growl of success? Here's a screenshot of the relevant criteria. 

![image](https://user-images.githubusercontent.com/33670923/59544804-5b6e3d00-8eca-11e9-935b-947115943305.png)

Right now, it growls: 

Success
Activity X was successfully deleted.

**Comment by jennyhavah** [comment]
Text change made. 👍
