### ISSUE TITLE
Styling cleanup

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1261]
Catchall for look/feel items that are … not quite … right

## General
- [x] <s>Select form elements (#1270)</s> Deferred to Poblano
- [x] <s>Multiselect form elements & children (e.g. tag badges) (#1271)</s> Deferred to Poblano
- [ ] Housekeeping (#1289)
- [x] <s>Replace "N/A" with em-dash (—) in displays of empty values (#1313)</s> Deferred to Poblano

## Admin Screens
- [x] Pane layout, vertical rhythm etc.
- [x] Flyout filter sidebar ala IPTT (#1262)
- [x] Overhead filters (#1263)
- [x] Table styling (#1264)
- [x] Add [object] buttons (#1265)
- [x] Accordion style (#1266)
- [x] Pager (#1267)
- [ ] <s>Loading/spinner animation</s> Deferred indefinitely
- [x] Virtual tables (#1287)

### [Edit an item] accordion folds
- [x] Vertical tabs (#1268)
- [x] Save/reset buttons (#1269)

### Status/History pane
- [x] Table styling (#1272)

### User: Programs and Roles pane
- [x] Select all button (#1273)
- [x] Table styling (probably related to #1272?)

### Disaggregation styling
- [x] Disaggregations in edit country pane (#1334)
- [x] See #1206 in Poblano

### Change log
- [x] Truncation & overflow (#1276)

**Comment by RickieT** [comment]
**QA PASSED**
* I'm comfortable passing this now, I've been across the whole site during my test pass and haven't come across any isssues with styling that were not already reported and fixed
