### ISSUE TITLE
RF builder: Link one or more indicators to a level, edit, and reorder them

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1275]
# Stories
1. As I build my program's Results Framework (RF), I can add indicators to each level as I go.
2. I can edit indicator details directly from the RF builder.
3. I can change the order in which my indicators are listed within a level.

# Acceptance criteria

**Precondition:** I am about to edit an empty RF level form at any level.

## Scenario 1: Before I type in the RF level text box

![image](https://user-images.githubusercontent.com/33670923/59528970-8fc70680-8e94-11e9-90de-d823401b2ed9.png)

- [x] 1. There is a button under the "Assumptions" text box that says "Save [RFtier] and add indicators". [RFtier] is in title case -- i.e. Outcome or Intermediate Objective. 

- [x] 2. The button is in an _inactive state_ until you type something in the RF level box. 

## Scenario 2: After I type in the RF level text box

![image](https://user-images.githubusercontent.com/33670923/59528980-9c4b5f00-8e94-11e9-9d87-c2295df39b8b.png)

- [x] 1. The Assumptions text box is now active. 

- [x] 2. I can now click the "Save [RFTier] and add indicators" button.

## Scenario 3: After I click "Save [RFTier] and add indicators"

![image](https://user-images.githubusercontent.com/33670923/59529175-209de200-8e95-11e9-9df2-c94863065086.png)

- [x] 1. The "Save [RFTier] and add indicators" is replaced by the Indicator add/edit/delete/reorder box.

- [x] 2. The title of the box is "Indicators linked to this [RFTier]". <-- the tier should always be Title Case.

Note: We are eliminating the 2-step process and going straight to the indicator form. See #1279 for details on indicator creation and save flow.

![image](https://user-images.githubusercontent.com/33670923/57661587-6a4a9280-75a0-11e9-8af0-e58daa023a4d.png)

- [x] 1. "Program Objective" multi-select menu is replaced by a **single-select** menu with the label "Result level*" with an asterisk to indicate that it is required

     - [ ] 1.1. We are not removing program objectives from the Django admin. We are adding a feature to make it easy to import these values -- see #1312.

- [x] 2. The above menu is automatically set to the current level that is in the process of being added, and is _inactive._ In other words, you can't be in the middle of adding brand new Outcome 2.2 and then assign its indicator to some other level. (After you save the current level, it's a different story.)

### I save by clicking the "Save and close" button

![image](https://user-images.githubusercontent.com/33670923/54461990-6da1d900-472b-11e9-85ad-759fcfe8f134.png)

- [x] 1. All indicator details are saved. 

- [x] 2. Indicator setup form closes.

- [x] 3. In the lower left corner of the page is an auto-dismissing success message: Indicator was saved and linked to [RF Level][RF number].

- [ ] 4. New indicator appears in the "Indicators linked to this [RF level] area.

     - [ ] 4.1. ~Desirable but not a must have: It would be nice to have a brief "flash highlight" behind the new indicator to draw attention to it.~ I no longer think this is necessary. You immediately see the new indicator in the list -- that's plenty.

     - [x] 4.2. The indicator text field is inactive, but you can hover to see the full text. 

     - [x] 4.3. Next to the indicator text field is a "Settings" button with gear icon. Clicking it reopens the indicator setup modal.

     - [x] 4.4. Drag-and-drop and keyboard reordering is available when there are at least two indicators. If there is only one, the reordering mechanisms should be hidden or inactive.

- [x] 5. In the upper right corner of the indicator area, there is a question mark icon with a tooltip: To remove an indicator: Click “Settings”, where you can reassign the indicator to a different level or delete it.
![image](https://user-images.githubusercontent.com/33670923/54462145-f3be1f80-472b-11e9-8362-aebc3478e7ec.png)

### I save by clicking the "Save and add another" button

![image](https://user-images.githubusercontent.com/33670923/57661774-12f8f200-75a1-11e9-9510-3738a2bf5133.png)

- [x] 1. All indicator details are saved.

- [x] 2. The indicator setup modal is replaced by a fresh "Add indicator" modal.

- [x] 3. In the lower left corner of the screen -- _**not the modal**_ -- is an auto-dismissing success message: Indicator was saved and linked to [RF level][RF number].

- [x] 4. Behind the modal, the new indicator is saved in exactly the same way as if you'd clicked "Save". So if you were to X out of that second "add indicator" modal before finishing, you'd see the indicator you previously saved underneath.

## Scenario 5: I click a saved indicator's "Settings" button after saving the RF level.
- [x] 1. The _Results Framework level_ field is now ACTIVE. I can now reassign the indicator to a different RF level.

     - [x] 1.1. In the single-select RF level menu, options are listed in hierarchical order and include the number.

     - [x] 1.2. Edge case: If I pick "--------" in the RF level menu and tab out or attempt to submit the form, I get the standard "Please complete this field" required field validation message and can't submit.

**Note:** Reassigning an indicator to a different RF level is covered in #1282 -- we must prompt for a rationale and log the change.

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by sanjuroj** [comment]
@jenny Are the link colors for the "Add indicator" and "Save <tier> and add indicators" links correct?  Should both be blue?  In the component Cameron created for the "Add Indicator" button, the link is green and since it's a shared component, I was wondering if the color is different for different purposes, or if it should actually be green, unlike the mockup.

**Comment by jennyhavah** [comment]
@sanjuroj Let's defer to shared components unless there's a good reason not to -- like contrast that's too low. (Based on what you just showed me on your screen, that doesn't seem to be an issue.)

**Comment by jennyhavah** [comment]
@sanjuroj Can you please remove this "No indicators" string and just make sure there's some padding above and below the "Add indicator" button? I don't think it adds useful information.

![image](https://user-images.githubusercontent.com/33670923/59727899-86b79b80-91ec-11e9-8b04-748ff5a8e0d5.png)

Here's the mockup for reference -- ignore the blue link color.

![image](https://user-images.githubusercontent.com/33670923/59727935-a5b62d80-91ec-11e9-875a-7e759b1d70f6.png)

**Comment by jennyhavah** [comment]
@sanjuroj I have a question regarding this criteria:

![image](https://user-images.githubusercontent.com/33670923/59728041-368d0900-91ed-11e9-8332-dc658079a52e.png)

I'm still seeing the Program Objectives menu. My assumption is that this is not something I should be concerned about for this particular ticket -- i.e. it should be addressed as part of #1286. Is that right?

**Comment by jennyhavah** [comment]
@sanjuroj I'm not seeing the tooltip described here:

![image](https://user-images.githubusercontent.com/33670923/59728358-91733000-91ee-11e9-86c5-6b610ffcef93.png)

When I click the question mark, it just highlights like this:

![image](https://user-images.githubusercontent.com/33670923/59728366-9c2dc500-91ee-11e9-8269-255616d28e14.png)

**Comment by sanjuroj** [comment]
@jennyhavah Yes, I considered the change in program objectives part of #1286.

**Comment by jennyhavah** [comment]
PASSED. "No indicators" string removed. Tool tip is working.
