### ISSUE TITLE
Refactor & redesign changelog (was: Change Log Needs styling: Truncation)

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1276]
Changelog construction needs a little refactoring and love. See also child tickets:
- [x] #1304 Re-implement collapsing changelog entries
- [x] #1305 Replace nerdy change_type values with human-readable values
- [x] #1306 Replace nerdy field names with human-readable names
---

## Original ticket:
The change log has no sorting options, and the styling here is less than desired, with odd cut offs of information in the before and after columns, especially with changes that are long. 

![image](https://user-images.githubusercontent.com/23220180/54294926-4f8f7980-456f-11e9-90a9-60ab6c795cda.png)

**Comment by axoplasm** [comment]
Wooohooo this is much bigger than I realized.

**Comment by RickieT** [comment]
**QA - FAILED**
https://tola-activity-dev2.mercycorps.org/tola_management/audit_log/480/

I made numerous changes to some indicators, the items in the change log will not expand so I can view the changes made.

**Comment by RickieT** [comment]
**QA - PASSED: Confirmed**

As part of testing:
 #1304 Re-implement collapsing changelog entries
 #1305 Replace nerdy change_type values with human-readable values
#1306 Replace nerdy field names with human-readable names

This ticket is ready for deploy. Looks great!
