### ISSUE TITLE
Add indicator flow: Move "Add" screen into modal and rethink object creation

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1279]
**Note:** This ticket is connected to #1275 that covers adding indicators to RF levels.

# Stories
1. When I add an indicator to a program, I don't lose context of wherever I came from -- be it the program page or the new RF builder.
2. It's not so easy to -- accidentally or intentionally -- add an indicator to my program with a bunch of missing required fields.

**Affects the following task flows:**
1. Adding an indicator from the program page/
2. Adding an indicator from an RF level.

**Does not address:** Editing saved indicators (including the RF level to which they are linked) after results are added, and logging changes. (Covered in #1282)

# Acceptance criteria

## Add indicator modal

~We are moving the "Add indicator" form into a modal. UI/interaction details specific to the RF builder (assigning levels, etc.) are covered in #1275 Scenario 3.~ We no longer need a two-step process, because we are no longer offering DIG indicators as part of Satsuma. (See comment thread.)

![image](https://user-images.githubusercontent.com/33670923/57714619-c1e11080-7629-11e9-8167-fc7efbc0766e.png)

- [x] 1. Until an indicator is saved, the title of the form is "Add indicator" with no secondary title.
- [x] 2. After an indicator is saved, the title becomes [RF tier] indicator [indicator number]. (This is in place of "Indicator setup". The subtitle becomes the text of the indicator. 

- [x] 3. If I'm adding an indicator from the RF builder, the Result level field is pre-populated.

     ![image](https://user-images.githubusercontent.com/33670923/57661291-0a9fb780-759f-11e9-9904-04376024e035.png)

## Add indicator form scenarios

**Note:** The following indicator form scenarios apply regardless of where you came from -- RF builder, program page, or IPTT. 

### Scenario 1: I exit prior to creating targets

![image](https://user-images.githubusercontent.com/33670923/57661339-4d618f80-759f-11e9-87e1-d471a260dcbe.png)

_Reminder: A new indicator is no longer created, prior to targets being completed. (See #1581 -- Light the Create Targets button on fire.)_ 

- [x] 1. At this stage, if I simply exit the browser or my computer crashes, the indicator is lost, end of story. But if I attempt to dismiss the indicator setup modal by clicking "X" or clicking outside the area, the system presents me with a red danger message positioned in the lower left corner of the modal.
     - [x] 1.1. Main message: This indicator is missing required details and cannot be saved.
     - [x] 1.2. Prompt message: Are you sure you want to continue? <P>

- [x] 2. If I click "Cancel", the danger message closes and I can continue editing the indicator setup modal.

- [x] 3. If I click "OK", the following things happen:
     - [x] 3.1. The danger modal closes.
     - [x] 3.2. The indicator modal closes.
     - [x] 3.3. The indicator object is not saved; you see no signs of it on the program page or RF builder.

### Scenario 2: After I complete all required fields and click "Save and close"

**Notes:** 
1. Ticket #1275 addresses what happens when you add an indicator from the RF builder. The following applies when I'm adding an indicator from the **program page.** 
2. The following flow also applies if I'm editing a previously saved indicator from the program page or IPTT, as long as all fields are complete.

**Save and close from program page**
![image](https://user-images.githubusercontent.com/33670923/54459929-53fd9300-4725-11e9-9963-6ce5069cbdd0.png)

**Save and close from IPTT**
![image](https://user-images.githubusercontent.com/33670923/59546515-844efc00-8ee3-11e9-8ad3-d500c38b5e06.png)

- [x] 1. The modal closes, the indicator is saved, and I can find it on the program page or IPTT.
- [x] 2. I see an auto-dismissing Success Growler in the lower left corner of the program page: Indicator [number] was saved and linked to [RF level][RF number].

### Scenario 3: I complete all required fields and click "Save and add another"

**Note:** Ticket #1275 addresses what happens when you save and add another indicator from the RF builder. The following applies when I'm saving and adding another indicator from the **program page*:

**Save and add another from program page**
![image](https://user-images.githubusercontent.com/33670923/57661460-d082e580-759f-11e9-931f-a004bc12abae.png)

- [x] 1. The indicator is saved and I can find it on the program page or IPTT.
- [x] 2. The indicator setup form is replaced by a fresh "Add indicator" form.
- [x] 3. I see an auto-dismissing Success Growler in the lower left corner of the program page or IPTT: Indicator [number] was saved and linked to [RF level][RF number].

## Housekeeping (where applicable)
- [x] Unit test/s written 
- [x] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by KennyMonster** [comment]
@jennyhavah In the case of DIG indicators, would it be the case that the info still needs to pull from the DIG server and auto-populate the form? There's some details here about saving "sector", "level", and "indicator type" which all seem to be imported from DIG and saved during creation as it stands.

**Comment by jennyhavah** [comment]
@KennyMonster Yes, we need to pull from the DIG server and auto-populate form fields with one important exception: If we currently import an indicator number, let's NOT do that because it will interfere with auto-numbering in #1253. 

I included the DIG pull criteria in #1275, but if it would be more usefully placed in this ticket, please feel free to cut and paste.

Regarding the specific fields auto-populated -- I didn't list those out, probably because it would have been time consuming to try and test out various DIG indicators to see what's pulled. I figured it might be easier to tell from the back end.

**Comment by KennyMonster** [comment]
Per @jennyhavah, we can now remove the DIG integration for now to simplify this.

https://mercycorps.slack.com/archives/C4KFV2VUY/p1557765457088900

**Comment by KennyMonster** [comment]
@jennyhavah Since the DIG integration is being removed, do you have any issue with removing the initial form that asks for the Indicator name?

![initial add indicator screen](https://user-images.githubusercontent.com/33670923/54459840-13057e80-4725-11e9-9e91-2185b12a12ff.png)

If you can imagine the above without the DIG integration, you are left with displaying the program name, program country, and a form field for the indicator name. Since the indicator form already has a field for the indicator name, it seems silly to divide this up into a 2 step form.

**Comment by jennyhavah** [comment]
@KennyMonster You're absolutely right! We can go straight to the summary tab of the main indicator modal. I'll make some tweaks to the story to reflect this.

**Comment by KennyMonster** [comment]
>  2.1. I no longer see the "Form data saved" message. (It draws your attention away from the much more meaningful system feedback of seeing your freshly generated targets.)
>  2.2 Instead of auto-scrolling you UP to the top of the page to show you an unhelpful message, we auto-scroll you DOWN to the title of the target creation area -- e.g. "Annual targets" or "Midline and endline targets".

@jennyhavah Is this true for both the creation and update form, or just the creation form?

**Comment by jennyhavah** [comment]
@KennyMonster Yes, this is true for both creation and update.

**Comment by KennyMonster** [comment]
@jennyhavah 

I'm at a bit of an impasse with target creation on the new indicator form. The issue is that utilizing the existing codepath of target creation (e.g. pressing Create Targets button), and avoiding the pitfall of redoing Winterhawks, strictly requires having the Indicator already exist in the DB. In other words, the existing code was written for the indicator update form, and retroactively fitting it to the creation form isn't feasible without re-writing it with different base assumptions.

This brings us back to doing a 2-step workflow where the first step is to save once to create the indicator, and the second is to populate target values and save again. There's a few ways to approach this, both with and without a Create Targets button, but in all cases I can think of, it breaks the logical flow of a "Save and close" and "Save and add another".

It might be good to discuss the options with changing to a 2 step workflow, or discuss doing somewhat heavy changes to existing periodic target creation and saving code.

**Comment by KennyMonster** [comment]
@jennyhavah So the good news is now that the "Create targets" button is a smoldering pile of ash in the corner, I'm pretty sure the entirety of "Scenario 2: I exit after creating targets but prior to entering all required target values" can now be crossed out from the spec!

**Comment by camgnostic** [comment]
@jennyhavah the spec says
>  1. Until an indicator is saved, the title of the form is "Add indicator" with no secondary title.

>  2. After an indicator is saved, the title becomes [RF tier] indicator [indicator number]. (This is in place of "Indicator setup". The subtitle becomes the text of the indicator.

But I can't find a way to get to the scenario of "after an indicator is saved" - can we safely remove this part of the spec?  The only buttons I have on the form are "save and close" or "save and add another" (or cancel) and neither of those cases leads to the form staying open with a new title, correct?

**Comment by jennyhavah** [comment]
@KennyMonster I updated Scenario 2 to cover a situation _before results are linked to an indicator_ where you can currently delete targets with no confirmation prompt whatsoever. (Ticket #1282 covers what happens after results are linked.)

**Comment by jennyhavah** [comment]
@KennyMonster Regarding Scenario 3:

For _saved_ indicators -- regardless of where you access them -- RF builder, IPTT, or program page -- I'd like the buttons to be:

Save and close
Cancel

Right now it's still "Save changes".

And I'm not seeing the growls of success as illustrated in the ticket. I'm still seeing the old "form data saved" in a green box embedded inside the indicator setup form.

**Comment by KennyMonster** [comment]
I have re-tested the target deletion for all target types both with and without results and was prompted each time, so I think we are good there.

I've also pushed changes to address the button label and "Growl of success" when updating an indicator as well.

If the indicator is not using the new RF, then the growl just displays: "Success! Indicator updated." to go along with "Success! Indicator created." on the create form.

**Comment by KennyMonster** [comment]
It's also worth mentioning the update modal form now closes on "Save and close", which is a bit of a departure from the previous behavior. Seems necessary for a "Save and close" button though!

**Comment by jennyhavah** [comment]
@camgnostic Regarding your question:

> But I can't find a way to get to the scenario of "after an indicator is saved" - can we safely remove this part of the spec? The only buttons I have on the form are "save and close" or "save and add another" (or cancel) and neither of those cases leads to the form staying open with a new title, correct?

I meant after it's saved, _when you reopen it_, you see the title as described. Not that it updates inside the indicator form while it's still open... because -- as you point out -- there is no longer a "Save changes" button that leaves the form open.

**Comment by jennyhavah** [comment]
PASSED. All acceptance criteria are met.

@KennyMonster I found a couple of issues in the course of testing this ticket, that I just filed and assigned to you -- #1683 and #1681.
