### ISSUE TITLE
RF builder: Log changes and prompt for rationales

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1282]
# Stories
1. **Program team:** We can easily tell the story of how our program logic evolved over time, as theories of change were tested and we adjusted program strategy accordingly. We can also protect ourselves when questions are raised about our performance and how we're measuring impact.
2. **Internal stakeholders:** I can ensure that our program teams are meeting agency standards for transparency and accountability, by making sure that changes to program logic are well documented.
3. **External stakeholders / auditors:** I can easily pinpoint and follow up on changes to program logic to ensure that the changes are valid and not an instance of "moving the goalposts." 
4. **Person building/managing the Results Framework (RF):** I'm not cursing out loud because the system is prompting me for rationales _all the damn time._

# Acceptance criteria

## _When_ do we prompt for rationales and log changes?
The trigger point for rationale prompts and change logging for any given RF level is whether or not there is an indicator linked to it.

- [x] 1. **BEFORE I link any indicators:** I am NOT prompted for a rationale when I save changes to the RF level text or assumptions, and changes are NOT logged.

- [x] 1.2. **AFTER I link indicator/s to my RF level and save changes:** From there on out, I am prompted for a rationale for a number of actions described below.

## Where does the prompt go and what does it say?

![image](https://user-images.githubusercontent.com/33670923/57562373-e9448e80-7346-11e9-84f4-525eff9a41ea.png)

- [x] 1. The prompt is always positioned in the lower left corner of the form you're editing, because that is where your attention is already focused.

- [x] 2. We use the same style of prompt we introduced with Papaya. It says: 
Warning <-- maybe, see #1330
Your changes will be recorded in a change log. 
For future reference, please share your reason for these changes.

### RF builder
I am prompted when:
- [x] 1. I modify the text of the RF level.
- [x] 2. I modify _already saved_ Assumptions text. 
- [x] 3. When I _delete_ saved Assumptions text without replacing it.

I am NOT prompted when:
- [x] 1. I add Assumptions text where there previously was none.
- [x] 2. I change the order of linked indicators

### Indicator setup form

![image](https://user-images.githubusercontent.com/33670923/57739322-0390ac00-7668-11e9-8e28-1521833e6aab.png)

The following user actions trigger prompts regardless of whether the indicator setup form is launched from the RF builder, program page, or IPTT gear icons.

**Reminder:** When you add an indicator to an RF level in the RF builder, the _Result level_ field is INACTIVE because you've already told the system which level you're adding the indicator to. This field only becomes editable after you save the RF level. For more details on this topic, see #1275.

- [x] 1. When I _reassign_ an indicator's result level. (Saved RF levels only)
- [x] 2. When I _unassign_ an indicator's result level and do not select a new one. (Saved RF levels only)

## How do I get to the change log from the RF builder?

- [x] 1. The RF change log is accessed via a link underneath the template box. It's a simple text link, using the same icon we use on buttons elsewhere.

![image](https://user-images.githubusercontent.com/33670923/55196621-207f2780-516d-11e9-8dea-1139f26da95d.png)

## Modifications to the change log itself

![image](https://user-images.githubusercontent.com/33670923/56239614-54e85400-6046-11e9-8798-a161d56c00d9.png)

- [x] 1. Add a column with the header "Result Level" to the right of "Date and Time"

- [x] 2. The value for that column is [RF tier][RF level # if exists]
     Examples: Goal, Outcome 1, Output 1.1, Activity 1.1.1

     - [x] 2.1. If a program is still using old levels, then that value can be used -- i.e. Goal, Outcome, Output, etc. with no numbers. <P>

- [x] 3. Remove "No." column and incorporate indicator numbers into the Indicator column itself.

     - [x] 3.1. The format is **Indicator [indicatorNumber]:** Indicator text  <-- note bolding. For example:
     **Indicator 2a:** Indicator text here
     **Indicator 2.2a:** Indicator text here
     **Indicator 2.2.2a:** Indicator text here <P>

- [x] 4. All of the above modifications to the change log are reflected in the Excel export.

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by sanjuroj** [comment]
@jennyhavah Should the rationale prompt be similar to the one that appears on the indicator modal?  I'm seeing this: 

<img width="358" alt="Screen Shot 2019-06-20 at 11 00 16 AM" src="https://user-images.githubusercontent.com/6685499/59870654-ca281c00-934a-11e9-9b73-d951d890eff8.png">

The one in the spec above looks somewhat different.

**Comment by jennyhavah** [comment]
@sanjuroj I think you're talking about the styling? Yes, it can be the same type of prompt we're using on the indicator form. The mockup represents the style Paul and I eventually want to get to, doesn't need to be implemented for Satsuma.

**Comment by hannalcamp** [comment]
I'm seeing a couple issues:

1. When I edit a results level _without_ linked indicators, it is logged without a rationale prompt being issued.

![Screen Shot 2019-06-27 at 1 37 11 PM](https://user-images.githubusercontent.com/38020496/60295475-05919000-98e1-11e9-97b0-1690d90e4107.png)
![Screen Shot 2019-06-27 at 1 37 28 PM](https://user-images.githubusercontent.com/38020496/60295476-05919000-98e1-11e9-9d25-f2de89766469.png)

![Screen Shot 2019-06-27 at 1 39 18 PM](https://user-images.githubusercontent.com/38020496/60295536-3671c500-98e1-11e9-9134-b191a38c2086.png)

- [ ] When I add an assumption where one previously didn't exist, it is logged without a rationale prompt being issued.

![Screen Shot 2019-06-27 at 1 42 34 PM](https://user-images.githubusercontent.com/38020496/60295649-75077f80-98e1-11e9-8baf-c38d35dfd040.png)
![Screen Shot 2019-06-27 at 1 42 18 PM](https://user-images.githubusercontent.com/38020496/60295647-75077f80-98e1-11e9-8392-da02ffd03bd3.png)

- [ ] When I add/edit a results level, go to the change log, and then hit the "back" button to get back to the RF builder, the new/edited level does not appear correctly - I have to refresh the page to see it correctly.

**Comment by KennyMonster** [comment]
@hannalcamp I pushed a fix for issue 3, where data is out-of-date on back button. 

Issue 1 and 2 were an undocumented design decision that came out of a discussion, but it can be changed to only log on rationale prompt if that's ultimately the desired behavior.

**Comment by jennyhavah** [comment]
@KennyMonster If it's a low effort, low risk update, let's go ahead and only log when we're prompting for a reason for change.

**Comment by hannalcamp** [comment]
Looks good to me!
