### ISSUE TITLE
Migration plan for legacy indicator levels

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1286]
**Ticket depends on:** Partner Access roles/permissions and admin console.

**Affects:** Admin console, indicator setup form, program page, IPTT, indicator plan

# Stories
**Team with a program already in Tola by the time we release Satsuma:** 
1. We have the option to use the new results framework (RF) functionality, but are not forced to do so in order to keep entering and tracking indicators in Tola.

2. If we do decide to use the new RF functionality, we can take our time building it out and linking indicators to it. In the meantime, we see indicators organized the way we're used to seeing it, by the original levels. Once the RF is in place, we can "flip a switch" to see indicators organized by the new RF. 

Definition of "existing program": For the purpose of this ticket, we are referring to any program that -- at the moment we deploy Satsuma -- already has at least one indicator with one of the _old generic levels_ selected.

# Acceptance criteria

## Admin console setting

- [x] 1. If (and _only_ if) I have Basic or Super admin access to a program, I can toggle between two indicator numbering options in the Programs area of the admin console.

     - [x] 1.1. **Where does this happen?** As described in #1288, let's add a new _Settings_ tab -- in between the _Profile_ and _Status and history_  tabs.

     ![image](https://user-images.githubusercontent.com/33670923/58915883-e1be9e00-86d6-11e9-811b-f8cd41049710.png)

     - [x] 1.2. **The second setting only appears for existing programs.** It will not be included with any new programs added after Satsuma is launched.

     - [x] 1.3. The setting is labeled "Indicator grouping" and there is a single checkbox with the following text -- please note bolding.
     **Group indicators according to the results framework:** After you have set a results framework for this program and assigned indicators to it, select this option to retire the original indicator levels and view indicators grouped by results framework levels instead. This setting affects the program page, indicator plan, and IPTT reports.

     - [x] 1.4. The box is _unchecked_ by default for existing programs.

### When "Indicator grouping is UNchecked
     
- [x] 1. The **_old_** Level field remains on the Performance tab. 

     - [x] 1.1. It is editable _for both new and existing indicators._ (A program may need to add new indicators in the middle of the implementation period, and will need to assign it to a level.)

     - [x] 1.2. _Level is still a required field_ and the system prompts me if I attempt to save without a level. (The IPTT and other pages must have this information in order to order indicators appropriately.)

     - [x] 1.3. Change the field label from "Level" to "Old indicator level" with an asterisk,

     - [x] 1.4. Next to the label is a question mark tool-tip that says: Indicators are currently grouped by an older version of indicator levels. To group indicators according to the results framework, an admin will need to adjust program settings.

     ![image](https://user-images.githubusercontent.com/33670923/58915893-ea16d900-86d6-11e9-84b8-84e6f3cafa8a.png)

- [x] 2. The _new_ Result level field on the Summary tab is editable, but is NOT a required field. There is no asterisk, and I am not prompted to fix it if I leave it blank -- before or after clicking save.  Note that because this is a required field only under certain circumstances, this cannot be set as a required field in the database.  The appropriate backend and frontend checks should be put in place to ensure that the correct type of level field is applied in the right circumstance.

### When "Indicator grouping" is checked

- [x] 1. The old Level field on the Performance tab is hidden. (Note: This field is NOT replaced by the RF levels field. As per #1275, we are placing the new RF levels field on the Summary tab.)

- [x] 2. There is no longer any validation connected to the hidden Level field. I can submit the form when this field is empty, _even in an edge case where the value is set to "------". (There are many indicators with no selection because somebody started to add an indicator and abandoned the process midway through, or because the indicator was added before the field was required.)

- [x] 3. The _new_ Result level field on the Summary tab is editable and **_IS required._** I describe this in greater detail in #1275 Scenario 3.

## Program page

- [x] **1. When "Indicator grouping is UNchecked:**  Indicators are grouped by the old levels.

- [x] **2. When "Indicator grouping is checked:** 
     - [x] 2.1. Indicators are grouped by the new RF levels.
     - [x] 2.2. I see the grouping toggle options, as described in #1311.

## Indicator plan

- [x] **1. When "Indicator grouping is UNchecked:**  Indicators are grouped by the old levels.

- [x] **2. When "Indicator grouping is checked:** 
     - [x] 2.1. Indicators are grouped by the new RF levels
     - [x] 2.2. I see the grouping toggle options, as described in #1303.

## IPTT reports (both types)

- [x] **1. When "Indicator grouping is UNchecked:** 
     - [x] 1.1. Indicators are grouped by the original levels in the table.
     - [x] 1.2. There is no "Group indicators" setting in the top dark gray section.
     - [x] 1.3. I see the original Levels filter menu in the bottom light gray section.
     - [x] 1.4. Indicators are grouped by the original levels in the Indicators filter. <P>

- [x] **2. When "Indicator grouping is checked:** 

     - [x] 2.1. Indicators are grouped by the new RF levels in the table.

     - [x] 2.2. I see the "Group indicators" setting in the top dark gray section, as described in #1298.

     - [x] 2.3. I see the new Levels filter menu in the bottom light gray section, that shows RF levels instead of the original ones.

     - [x] 2.4. Indicators are grouped by the new RF levels in the Indicators filter.

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by camgnostic** [comment]
Criterion 1.2 in this ticket is the one we need to come up with a good solution for going forward.  I am tagging @KennyMonster and @sanjuroj  and also @jennyhavah on this to make sure we are solving this going forward.

**Comment by jennyhavah** [comment]
@camgnostic Everything looks great, behaving as expected.

Regarding 1.2 -- Is the issue of how to determine "what is an existing program" solved? Wondering if it is okay to move this ticket to Passed testing.

**Comment by jennyhavah** [comment]
Slack response from Cameron, regarding 1.2: "I built it to be a 3-position switch: Pre-migration, Migrated, and Always-RF.  And starting with satsuma release all programs created will be set to Always-RF by default"
