### ISSUE TITLE
Indicator numbering options and migration plan

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1288]
**Ticket depends on:** Partner Access roles/permissions and Admin Lite.

# Issues
1. Provide a means for teams that really really really need to override indicator auto-numbering, to do so.
2. Provide a migration path for teams that have already manually entered numbers, to continue seeing their numbers until they are ready to group indicators according to the results framework (RF).

# Acceptance criteria

## Program settings tab added to admin section

![image](https://user-images.githubusercontent.com/33670923/55104619-f43dab00-5087-11e9-887e-8ba1d78918a8.png)

- [x] 1. If (and _only_ if) I have Basic or Super admin access to a program, I can toggle between two indicator numbering options in the Programs area of the admin section.

     - [x] 1.1. **Where does this happen?** Let's add a new _Settings_ tab -- in between the _Profile_ and _Status and history_  tabs. I'm intentionally keeping the tab name broad and generic so that it can accommodate a variety of program settings related to indicator numbering, migration from Levels to RF levels, and who knows what else in the future.

     - [x] 1.2. There are two toggle options -- please note the formatting details, particularly the bolding and red color used for warning text.

     **Auto-number indicators (recommended):** Indicator numbers are automatically determined by their results framework assignments.

     **Manually number indicators:** If your donor requires a special numbering convention, you can enter a custom number for each indicator. _Manually entered numbers do not affect the order in which which indicators are listed; they are purely for display purposes._

## Rules for older programs

The following apply to programs entered into Tola prior to the Satsuma launch

- [x] 1. I only see the "Group indicators by" checkbox. I do not see the numbering options. The system is still displaying manual numbers, when available.

- [x] 2. When I check the "Group indicators by" box, the numbering options appear _below_ rather than above. (Ignore the ordering in my mockup.)

- [x] 3. The default selection is Auto-number.

- [x] 4. The system remembers my manually entered numbers, so that I can toggle between Auto and Manual options.

- [x] 5. If I then uncheck the "Group by box", the indicator numbering options go away, and the system reverts to manual numbering.

- [x] 6. **Program page:** We include the oldLevel column, like so:

     ![image](https://user-images.githubusercontent.com/33670923/61085695-bfaaf080-a3e5-11e9-9d56-d7dad24149e7.png)

## Rules for newer programs

The following applies to all new programs entered into Tola, post-Satsuma.

- [x] 1. The first option (auto-number) is the default selection.

## Indicator setup form

- [x] 1. **If the auto-numbering option is selected, the following things are true:

     - [x] 1.1. On the indicator setup form, we hide the "Display number" field.

     - [x] 1.2. _We preserve any manually entered numbers in the database_, so that the program can toggle back and forth without redoing all of their numbers. (There are valid reasons why a program might want to switch back and forth -- produce an internal report with auto-numbers, produce a donor report with donor-numbers.

     - [x] 1.3. The title of the indicator form is [RF tier] indicator [indicatorNumber]: [IndicatorText]. So where today we say "Output indicator: Blah blah", we now say "Output indicator 1.1a: blah blah"

- [x] 2. **If the manual option is selected,** the following things are true:
     - [x] 2.1. The Number field that previously appeared on the Performance tab is now the second field on the Summary tab. It is renamed "Display number"

     ![image](https://user-images.githubusercontent.com/33670923/57325020-fb5fcc00-70bd-11e9-89a6-176ea201e065.png)

     - [x] 2.2. There is a tool-tip that says: This number is displayed in place of the indicator number automatically generated through the results framework. An admin can turn on auto-numbering in program settings. <P>

## Result form

- [x] 1. **If I choose the auto-numbering option:** The title of the result form is [RF tier] indicator [indicatorNumber]: [IndicatorText]. So where today we say "Output indicator: Blah blah", we now say "Output indicator 1.1a: blah blah"

## Where this selection manifests across the app

We need to make sure that numbering preferences are respected in the following places:

- [x] 1. Program page
- [x] 2. Indicator plan, including export
- [ ] 3. IPTT reports -- both types, including exports
- [ ] 4. Change log, including exports
- [ ] 5. Logframe -- both the export and web view 
- [x] 6. Indicator setup form title
- [ ] 7. Result form title

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by camgnostic** [comment]
Admin console setting and model field are done, moving back to "Ready" awaiting latest round of indicator form updates from @KennyMonster - I'll circle back around to this one once the indicator form updates are merged

**Comment by esinn** [comment]
Results from testing:

1. When I select the option of manually number indicators for an existing program but the option "Group indicators according to the results framework" is _**not**_ selected, when I go to the indicator set up form I cannot see the field "display number" on the summary tab of the indicator form (or the tool-tip text). Not sure if this is an issue or not b/c I didn't click on the indicator grouping option but it was a bit confusing.

2. Another point that I'm not sure is an issue or not is for existing programs, when the auto-numbering option is selected for an existing program but the option "Group indicators according to the results framework" is _**not**_ selected, the manually entered indicator numbers still display on the program page. Assuming these should be hidden??? 
![image](https://user-images.githubusercontent.com/13574772/60469001-32f77a00-9c10-11e9-9011-a51b52950a41.png)

There were a number of confusing interactions related to the indicator group option on the settings tab and what happens (or doesn't!) when it's not checked. If the default is to check the auto-number indicator option then we may also want to consider a default of checking the indicator grouping option.

**Comment by camgnostic** [comment]
Follow-up for the indicator grouping section (and I think we definitely need to write up an internal wiki page about it's behavior at least if not an external documentation):
- group indicators isn't selected by default because once selected you can't update or create indicators without assigning them an RF level, which you cannot do until you _create_ RF levels, which we didn't want to impose on programs as soon as we released (we wanted them to have the option to continue using Tola the way they had been until they were ready to switch)
- the state of "not migrated to RF" (group indicators box UNchecked) and also "auto-number indicators" checked is not well-defined.  This is the part I would love to clarify in a wiki especially.
- programs that are created after satsuma is released will not have the option of unchecking "group indicators by" - that option will be both checked and hidden (you have no choice but to group indicators by RF going forward)

**Comment by jennyhavah** [comment]
Not seeing the "Display number" field when "Manually number" option is selected.

**Comment by jennyhavah** [comment]
@camgnostic I think we need further clarification on the rules. Here's an example of where I still have a problem:

For this program, auto-numbering is selected by default, and the Group by box is unchecked. As Emily described above, we're still seeing the manually entered numbers:

https://tola-activity-qa.mercycorps.org/program/581/#/

We are intentionally overriding the old manual numbers, in the hopes that teams will adopt the new auto-numbering convention. This is why the criteria are to have auto-number selected by default, which means that they do NOT see their manually entered numbers unless they go into the admin and explicitly override it. If they check manual numbering, then they get to see the old numbers and the "Display number" field.

**Comment by jennyhavah** [comment]
@camgnostic Based on our conversation, I've substantially revised the acceptance criteria. To summarize: Older programs will not have the option to auto-number until they check the "group by RF" check box.

**Comment by camgnostic** [comment]
should be met! 
program is older than satsuma, has not migrated: "old" numbers always displayed, no numbering options in settings, "group by" option in settings visible and not checked
program is older than satsuma, has migrated: "old numbers" never displayed, numbering option visible in settings and defaulted to "auto", "group by" option in settings visible and checked
program is older than satsuma, has migrated, has checked manual numbering: "old numbers" displayed, numbering option in settings visible and set to manual, "group by" option in settings visible and checked
program is newer than satsuma: "old numbers" never displayed, numbering option visible in settings and defaulted to "auto", "group by" option in settings not visible
program is newer than satsuma and has checked manual numbering: "old numbers" displayed, numbering option in settings visible and set to manual, "group by" option in settings not visible

**Comment by jennyhavah** [comment]
@camgnostic See number 2 -- please reorder fields so that the numbering options appear _below_ the grouping checkbox... It's essentially become a kind of secondary set of options, so feels more natural for it to appear below.

**Comment by jennyhavah** [comment]
@camgnostic Edge case:

1. On an older program, check the "group by" box and save changes.
2. Now switch to manual numbering and save.
3. Now uncheck the "group by" box and save.
4. Now check it again and save. Because everyone would totally do that, right?

Expected: Default should be auto-number.
Observed: It "remembers" that you manually numbered it before.

**Comment by jennyhavah** [comment]
Last two issues are fixed.

I found a problem with the indicator numbering in the result form. Here's an example from VISTA:

Result form:

![image](https://user-images.githubusercontent.com/33670923/61090965-3ef3f080-a3f5-11e9-8909-d0a377876bd3.png)

Program page, for reference:

![image](https://user-images.githubusercontent.com/33670923/61090973-474c2b80-a3f5-11e9-8a1e-b36dc3a3a557.png)

**Comment by jennyhavah** [comment]
**Logframe:** If I am grouping by indicators and have _manual_ numbering checked, I'm not seeing the numbers in the logframe. Here's an example from Desarrollo Rural Inclusivo - Alternative Livelihoods for Coca Growers (ALGO Nuevo) that has numbers like  B-01, B-02, etc. 

![image](https://user-images.githubusercontent.com/33670923/61091182-07d20f00-a3f6-11e9-9ce8-593f86b37eb1.png)

Ideally, if there is a manual number, it'd say Indicator B-01: Blah blah.

If there is NOT a manual number, you'd just see the indicator without any "Indicator:" in front of it.

**Comment by jennyhavah** [comment]
**IPTT:** Can we remove the colons from the NO. column, across the board -- regardless of whatever combination of numbering and grouping is selected? (Not part of the original design, but just noticing it now for some reason.)

![image](https://user-images.githubusercontent.com/33670923/61091242-3d76f800-a3f6-11e9-8c3f-d826d469a968.png)

**Comment by camgnostic** [comment]
can't hurt to test, but I'll remove from both

**Comment by camgnostic** [comment]
- [ ] result form title
- [ ] logframe web
- [ ] logframe export
- [ ] iptt web (colons)
- [ ] iptt export (colons)

**Comment by jennyhavah** [comment]
Looks like we may have a regression with manual numbering. 

Here's what I see when the program is using OldLevels -- good

![image](https://user-images.githubusercontent.com/33670923/61163449-e723bb00-a4c2-11e9-987a-8d650f452193.png)

New levels with auto-numbering -- also good

![image](https://user-images.githubusercontent.com/33670923/61163468-00c50280-a4c3-11e9-86f2-7b10efcbb703.png)

But when it's set to manual numbering, the title still seems to be showing the auto-numbers.

![image](https://user-images.githubusercontent.com/33670923/61163522-57324100-a4c3-11e9-9515-f80e6ddb5bc0.png)

**Comment by jennyhavah** [comment]
Regarding the Logframe: I now see manual numbers in the Logframe. But when an indicator does not have a manual number saved, it still says "Indicator:"

Is it hacky/high level of effort to hide it if there is no number? (Totally low priority if so.)

**Comment by camgnostic** [comment]
Logframe: now only shows the word "Indicator" and the ":" when there is a number (automatic from level if RF + Auto-number, otherwise manually entered) and otherwise just shows the name.

Also added an explicit sort to the indicator plan (as there were certain situations where the implicit "sort by level_order" wasn't producing the correct sort output

**Comment by jennyhavah** [comment]
I'm no longer seeing the old number field when a program is NOT grouped by RF. To be clear, this is not the new "Display number" field, but the original number field, pre-Satsuma.

To reproduce, set this program to NOT group by RF, and look for the old number field in the indicator form.

https://tola-activity-qa.mercycorps.org/program/581/#/

**Comment by jennyhavah** [comment]
Also: For the edge case program with the sorting issue -- QA Jenny -- the "group by" filter is still unresponsive on the IPTT.

**Comment by camgnostic** [comment]
fixed old number field (was not registering that old programs use manual numbering due to redefinition of "manual_numbering" on recent fixes) - now shows "Number" for unmigrated programs, and "Display Number" with help text for migrated programs that selected "manual numbering"

**Comment by camgnostic** [comment]
The "Group by" filter isn't unresponsive, sorting that particular combination of levels in level order and output chain order looks the same  ( 1.1, 2.1, 2.2, 2.2.1 - that's the same if you're going from 1 -> 1.1 then 2 -> 2.1, 2.2-> 2.2.1 or if you're going all outputs (1.1, 2.1, 2.2) then all activities (2.2.1) etc.

**Comment by camgnostic** [comment]
One question - on the result form if an indicator is part of a program that is migrated to RF but the indicator does not currently have a result level, it currently says "Indicator: <indicator name>" is that acceptable?

**Comment by jennyhavah** [comment]
> One question - on the result form if an indicator is part of a program that is migrated to RF but the indicator does not currently have a result level, it currently says "Indicator: " is that acceptable?

@camgnostic Yes, that is fine.

**Comment by jennyhavah** [comment]
@sanjuroj When a program is set to Group by RF and auto-number, I am still seeing manual numbers on the program, and am seeing the old number field, like so: 

![image](https://user-images.githubusercontent.com/33670923/61232946-4f051c00-a6e4-11e9-90cf-412eff8d5875.png)

To reiterate, these are the rules:

1. Group by RF is UNchecked: I see the old Number field as shown above. I see manual numbers on the program page, if entered.

2. Group by RF is CHECKED, auto-numbering is selected, I do not see ANY sort of numbering field -- neither Number nor Display number. On the program page, I only see auto-numbers, otherwise no numbers at all, even if manual ones were previously entered.

3. Group by RF is CHECKED, manual is selected: I see the Display number field, like so:

![image](https://user-images.githubusercontent.com/33670923/61232773-ef0e7580-a6e3-11e9-8e4e-83430b2d9915.png)

On the program page, I see manual numbers if entered, no numbers if not.

**Comment by jennyhavah** [comment]
Since Cameron is out today and tomorrow, assigning this ticket to Sanjuro.

**Comment by sanjuroj** [comment]
@jennyhavah, I checked the combos of new and existing programs, Indicator grouping checked and unchecked, and auto-numbering on and off, and all of the criteria look ok (as we noted previously).  

The only problem I found was that a 500 error came up when a new program tried to switch from auto-number to manual numbering.  This bug was introduced on the 11th, which is why it wasn't caught earlier.  It was an easy fix and will be in the next push.

**Comment by jennyhavah** [comment]
@sanjuroj Thanks for investigating! As we saw on my machine, I was unable to reproduce the issue, and wonder if it may have been some weird caching issue that worked itself out.

Will consider this Passed and keep an eye out for a recurrence.
