### ISSUE TITLE
IPTT: Incorporate RF levels into the table and options into the sidebar

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1298]
# Stories

**Affected by:** Legacy indicator levels and our migration plan for those.  See the "IPTT" section in #1286.

**Affects:** Both types of IPTT report

1. Indicators in the IPT table are organized by Results Framework (RF) level
2. I can toggle between grouping indicators by result chain or by tier
3. I can filter my IPTT by one or more RF _tiers_ (Outcome, Output, Activity)
4. Exports reflect all new RF filter and grouping options.
5. Pins preserve all new RF filter and grouping options.

Note: See #1286 for details on how we're managing programs using the old levels.

# Mockups

## Indicators grouped by Results chain
![image](https://user-images.githubusercontent.com/33670923/55180095-1f86cf80-5146-11e9-8b72-f27749a08720.png)

## Indicators grouped by Level
![image](https://user-images.githubusercontent.com/33670923/55180106-27df0a80-5146-11e9-82bb-cc6b33bf2a59.png)

# Acceptance criteria

## 1. Indicators in the IPT table are organized by RF level

- [x] 1. RF levels have dedicated rows that display [RF Tier][RF# unless top level]: [RF level]
![image](https://user-images.githubusercontent.com/33670923/54856412-a3a90500-4cb7-11e9-814c-f609874edb77.png)

- [x] 2. Indicators that are unassigned to an RF level are grouped at the bottom of the table under a single row that says: Indicators not assigned to a results framework level
![image](https://user-images.githubusercontent.com/33670923/55180156-3fb68e80-5146-11e9-8b89-f75c9510ad12.png)

- [x] 3. The Level column is gone. (That column only existed because the IPTT was missing RF level rows.) 

- [x] 4. In the "No." column, update the string from just the indicator number to [RFtier][IndicatorNumber]. Example: Outcome 1a

![image](https://user-images.githubusercontent.com/33670923/54955673-2ece0900-4f0b-11e9-8b55-9a5db583f885.png)

## 2. I can toggle between grouping indicators by results chain or by tier

![image](https://user-images.githubusercontent.com/33670923/55106325-e12cda00-508b-11e9-9a37-4ac785651cd2.png)

- [x] 1. Under the Start and End period menus is a new single-select menu with the label "GROUP INDICATORS"

- [x] 2. There are two options to toggle between with no "null" option -- has to be one or the other:

     - [x] 2.1. by [2ndRFTier] chain -- i.e. for Mercy Corps it'd be "by Outcome chain".
          - [x] 2.1.1. This is the default selection.
          - [x] 2.1.2. Multi-word tiers are capitalized as special nouns, but the rest of the string is sentence case. For example: "by Specific Objective chain"

     - [x] 2.2. by Level -- where level refers to what we're internally calling "tier" -- Goal, Outcome, Output, etc.

- [x] 3. The default selection is Group by [2ndRFTier] chain

- [x] 4. When I toggle from one option to the other, the IPTT reloads with the indicators sorted by the chosen option.

## 3. **Indicator filtering features are updated to incorporate Results Framework**

- [x] 1. **IPTT table:** When I filter indicators, I see the RF level rows to which they belong in the IPTT table.

- [x] 2. **IPTT table:** Rules for showing/hiding RF level rows

     - [x] ~2.1. When I first load the IPTT, I see all RF level rows that exist, regardless of whether or not there are any indicators linked to them.~ NO LONGER TRUE. See #1661.)

          - [x] 2.1.1. I don't see the "Indicators unassigned to a Results Framework level" row when all indicators are assigned to RF levels.

     - [x] ~2.2. Changing anything in the top (dark gray) section **has no effect** on whether or not RF level rows are displayed or hidden...~ NO LONGER TRUE. As a result of #1661, if you change target frequency, you'll see different RF levels -- only the ones linked to indicators with that frequency.

     - [x] 2.3. When I use any of the filters in the bottom (light gray) section -- Levels, Types, Sectors, Sites, or Indicators -- the table HIDES any RF levels to which NONE of the returned indicators belong. Rationale: If my intention is to pin an IPTT that only includes indicators linked to the Outcome 1 chain or only includes Activity indicators, then all other RF levels are irrelevant noise.

- [x] 3. **Levels filter:** Generic levels replaced by RF tiers and results chains
There are two components to this filter -- RF tiers listed in hierarchical order, followed by results chains.
![image](https://user-images.githubusercontent.com/33670923/55043952-ac6e4380-4ff5-11e9-8eaf-79725c754a7d.png)
     - [x] 3.1. I can select a tier OR a results chain, never a combination of both.
     - [x] 3.2. **RF tiers:**  I see RF tiers in hierarchical order.
          - [x] 3.2.1. RF tiers with _no indicators_ linked to them are not shown. (General principle is not to include filter options that will return zero indicators.)
          - [x] 3.2.2. Filtering on an RF tier returns all indicators associated with all levels at that tier.

     - [x] 3.3. **Results chains:**  This refers to the 2nd RF tier _and all of its sub-tiers._ 

          - [x] 3.3.1. Between the levels and the results chains is a line break and the header "[SECONDTIER] CHAINS"
          - [x] 3.3.2. Results chains appear in numeric order.

          - [x] 3.3.3. The formatting is [RFLevel] [RFLevelNumber] and sub-levels: [RFLevel text]. For example, _Outcome 1 and sub-levels: Improve access to essential hygiene and NFI items for IDP and host community households in northern Syria_

          - [x] 3.3.4. Results chains with no indicators linked to ANY of its tiers are not shown.

          - [x] 3.3.5. Filtering on a results chain returns all indicators linked to the 2nd tier _and all of its sub-levels_

- [x] 4. **Indicators filter:** Indicators are grouped by RF levels
![image](https://user-images.githubusercontent.com/33670923/55044173-7bdad980-4ff6-11e9-8728-70cab8b8b258.png)
     - [x] 4.1. In the Indicators multi-select filter, I now see indicators grouped by RF level, in the same order as the IPTT table itself.

     - [x] 4.2. Indicator grouping reflects the current _Group indicators_ selection -- by [2ndtier] chain or by level.

     - [x] 4.3. The RF level is used as a header above each cluster of indicators, with a bit of space in between the groups. We only show the RF Level and number, not the full text of the RF level. For example, OUTCOME 1

     - [x] 4.4. The format for each option is [RFTier][Indicator #]: [Indicator text]

     - [x] 4.5. If an RF level has no indicators linked to it, it doesn't appear in the list.

## 5. IPTT Excel exports preserve all new RF filter and grouping updates
IPTT Excel export reflects the following updates, such that you see the table you are expecting, consistent with what is on the screen in the following ways:
- [x] 5.1. Group indicators by" option -- by tier or by chain.
- [x] 5.2. Levels filter -- now RF tiers.
- [x] 5.3. Indicators filter -- now includes grouping by RF level.

## 6. Pins preserve all new RF filter and grouping updates.
Pinned IPTT reports reflect the following updates, such that you see the table you are expecting when you click a pinned report from the Program page:
- [x] 6.1. Group indicators by" option -- by tier or by chain.
- [x] 6.2. Levels filter -- now RF tiers.
- [x] 6.3. Indicators filter -- now includes grouping by RF level.

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by jennyhavah** [comment]
@camgnostic I haven't started going through all the acceptance criteria yet, but right away noticed an issue that's relevant to this ticket, when testing another one:

I was trying to assign some RF levels to indicators on one of the QA programs. I successfully saved an RF level assignment. When I closed, I expected the IPTT to update, moving the indicator under the appropriate gray RF level bar. But instead, the row disappeared. Tried it a few times, behaved the same way.

**Comment by camgnostic** [comment]
I believe I have addressed that behavior in the latest round of bugfixes - can you test and let me know?

**Comment by jennyhavah** [comment]
@camgnostic Found an issue with the Levels filter. 

>  3.3.3. The formatting is [RFLevel] [RFLevelNumber] and sub-levels: [RFLevel text]. For example, Outcome 1 and sub-levels: Improve access to essential hygiene and NFI items for IDP and host community households in northern Syria

Check this out -- Looks like you're repeating the RFLevel text twice.

![image](https://user-images.githubusercontent.com/33670923/59243649-dd5a1f80-8bc5-11e9-89ab-14d31a41053d.png)

**Comment by jennyhavah** [comment]
@camgnostic Regarding criteria 4.3

> 4.3. The RF level is used as a header above each cluster of indicators, with a bit of space in between the groups. We only show the RF Level and number, not the full text of the RF level. For example, OUTCOME 1

Looks like you're using the format [RFTier][RFText] instead of [RFTier][RFnumber]

![image](https://user-images.githubusercontent.com/33670923/59243732-45a90100-8bc6-11e9-9f34-5f55bc46e735.png)

**Comment by jennyhavah** [comment]
@camgnostic Regarding exports and the Levels filter menu:

It seems to work as expected when I select an Outcome chain, but not when I select a level.

![image](https://user-images.githubusercontent.com/33670923/59244530-bbfb3280-8bc9-11e9-8718-803fffed02a5.png)

**Comment by jennyhavah** [comment]
@camgnostic Regarding pinning an IPTT after filtering with the Indicators filter.

When I check multiple indicators and then pin the IPTT, head to the program page and click on the pin, the pinned IPTT only displays **one** of the indicators, not all of them.

**Comment by camgnostic** [comment]
Fixed level display in multiple places (sortDisplay should be just "1" or "2" not "1.2.0.0" etc.
Fixed IPTT Export with tiers selected

**Comment by jennyhavah** [comment]
@camgnostic Almost everything checked out. I am still having some issues with exporting IPTTs filtered on levels.

Try going to Ann Viv Ansanmn, filtering on one or more Levels, and the exporting. I get an IPTT with no data in it -- just the header rows.

**Comment by camgnostic** [comment]
Got it!  Fixed - was a string/integer mismatch again

**Comment by jennyhavah** [comment]
@camgnostic Couple of minor formatting nitpicks that I noticed because I tried exporting an RF using a different template -- just let me know if the LoE is high on either one:

Can you left-align the Number row, and somehow avoid it getting chopped off when the tier name is long, like so?

![image](https://user-images.githubusercontent.com/33670923/59618259-b11a3380-90dc-11e9-801f-592d83cdc496.png)

**Comment by camgnostic** [comment]
> somehow avoid it getting chopped off when the tier name is long, like so?

Options to solve this:
 1) make the number column much wider for all reports
 2) attempt to determine how long the column needs to be and make it long enough for that report (reports will all look a little different)
 3) make the number column wrap

which would you prefer?

**Comment by jennyhavah** [comment]
@camgnostic Can you:

1. Left align the column.
2. Make it wrap.
3. Make it wide enough that Specific Objective 1a does not wrap to THREE lines. (Two is fine.)

Thanks!

**Comment by jennyhavah** [comment]
Looking good! Here's what I see:

![image](https://user-images.githubusercontent.com/33670923/59725584-ec9f2580-91e2-11e9-9d58-840e558e5ace.png)
