### ISSUE TITLE
Logframe: Web view 

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1315]
# Stories
1. **RF building person:** As I'm building out my results framework in the accordion outline-style UI, I can toggle to an easily scannable, tabular view that is more familiar to me in format, and that includes all of my assumptions without needing to manually open each level to see it.
2. **Program reviewer:** I can easily access a program's logical framework from the Program page, in a format that is familiar to me.

# Acceptance criteria

### Program page sidebar

![image](https://user-images.githubusercontent.com/33670923/55174175-31627580-513a-11e9-926b-a2b7237f537f.png)

- [x] 1. There is a link under "Results framework" called "Logframe" with a table icon to visually communicate the difference between the two. (The logframe format tends to be tabular while the RF format tends to be visually hierarchical. The actual phrases are somewhat interchangeable, so the icons communicate that the links are not actually redundant.)

### RF builder

![image](https://user-images.githubusercontent.com/33670923/55174945-9f5b6c80-513b-11e9-87ee-d77219ff52ec.png)

- [x] 1. Before the first RF level is saved, _there is no link_ to the Logframe view.

- [x] 2. After the first RF level is saved, a link appears in the upper right corner -- the table icon followed by "View logframe"

- [x] 3. If a program is not yet grouping indicators by RF levels (Program settings box is unchecked), then the following things are true:

     - [x] 3.1. No link to the Logframe on the program page

     - [x] 3.2. On the RF builder page, the Logframe link appears, but is disabled with a help text popover that says: Indicators are currently grouped by an older version of indicator levels. To group indicators according to the results framework and view the Logframe, an admin will need to adjust program settings.

## What's in the Logframe web view

![image](https://user-images.githubusercontent.com/33670923/59897331-156d1980-93a1-11e9-91ca-9086a4ae92bc.png)

- [x] 1. Page title is "Logframe"

- [x] 2. Near the title is a link back to the program's RF builder -- the tree diagram icon followed by "View results framework"

- [x] 3. A table with four columns: 

     - [x] 3.1. **Result Level** in the following format -- [RFlevel][RFnumberIfExists]: [RFtext]. 

          - [x] 3.1.1. This column has a gray background to set it apart from the other columns. Note that the result level cells rowspan the indicator rows. <P>

     - [x] 3.2. **Indicators** in the following format -- Indicator [IndicatorNumber]: [IndicatorText]

     - [x] 3.3. **Means of verification** -- Content comes from the Data Acquisition tab of the indicator setup form.

     - [x] 3.4. **Assumptions** -- Content comes from the Assumptions field of the RF level. Note that these cells rowspan the indicator rows.

- [x] 4. Any indicators unassigned to RF levels are grouped at the bottom in a Result Level called "Indicators unassigned to a results framework level".

## Toggling between grouping options

![image](https://user-images.githubusercontent.com/33670923/55174223-450ddc00-513a-11e9-81ab-a22b14556762.png)

- [x] 1. In the upper right corner, just above the table, is a single-select identical in function to the one we're using in the IPTT filter panel. Consider long RF level names translated into French.

     - [x] 1.1. The form field label is "Group indicators:"

     - [x] 1.2. The menu is a single-select with two toggle options and no "null" type value such as "-----". The search function should be OFF, since there are only two options.

     - [x] 1.3. The default selection is "by [2ndRFtier] chain". For the MC template it would be "by Outcome chain" and for the EC template it would be "by Specific Objective chain". Please note the capitalization -- "by" is lower case, and the RF tier is title case. 

     - [x] 1.4. When the menu is set to "by [whatever] chain", the table is organized hierarchically -- e.g. for Mercy Corps template it would be Goal, Outcome 1, Output 1.1, Activity 1.1.1, Outcome 2, etc.

     - [x] 1.5. When the menu is set to "by Level", the table is organized by RF tier -- e.g. for Mercy Corps template it would be Goal, all Outcomes, all Outputs, all Activities.

## Exporting the logframe to Excel

- [x] 1. In the upper right corner is an Excel button. Clicking it initiates the downloading of an Excel export. The export is covered in ticket #1314.

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by jennyhavah** [comment]
@camgnostic Would it be easy or hard to eliminate the colspans? 

For example, here I'd like to see the vertical lines in between the rightmost 3 columns.

![image](https://user-images.githubusercontent.com/33670923/59880677-817c5d00-9362-11e9-8def-32499841d96c.png)

And here, I'd like to see the vertical line in between columns 2 and 3.

![image](https://user-images.githubusercontent.com/33670923/59880692-893c0180-9362-11e9-83d7-f2c81a652d6a.png)

**Comment by jennyhavah** [comment]
@camgnostic Looks like this piece isn't done yet. Will hold off on testing that, as well as Exports, until you let me know it's ready:

![image](https://user-images.githubusercontent.com/33670923/59881071-88f03600-9363-11e9-86aa-5bcc89ac0a1b.png)

**Comment by jennyhavah** [comment]
PASSED. All acceptance criteria met. I created a separate ticket for styling details -- #1715.

**Comment by sanjuroj** [comment]
@jennyhavah Question about the visibility of the logframe link on the program page at the top of this ticket.  We are allowing the logframe to be viewed even if they haven't flipped the Indicator Grouping switch.  But that means that it's possible that none of their indicators will be assigned to an RF, which means the link on the program page will be invisible.  This creates an awkward situation where they need to create the RF and add at least one indicator to the RF level to see the link.  Should we make the link visible as long as they have _either_ an RF level _or_ and old-style level assigned (which will be most programs)?  Or just make it always visible so they can have a list of indicators sorted by "number" in a logframe format?

**Comment by jennyhavah** [comment]
@sanjuroj I'm realizing that I didn't call this out in the ticket, but I'd like the same rules to apply on the program page, that apply on the RF builder page. If a logframe has at least one RF level, we show the link on the program page. If not, we don't. This should be independent of whether or not the "group by levels" box is checked. Does that work?

**Comment by sanjuroj** [comment]
@jennyhavah Follow up from the decision to remove the Logframe links from the Program and RF builder pages until Indicator Grouping is enabled.  We talked keeping the Logframe link on the RF builder, but having it disabled with a help popover to tell the user how to enable it.  Can you provide the text to put in the help message? Note that it's not possible to link directly to a program's admin (the filters are not reflected in the URL).  Also, I'm assuming that the only the RF builder would have this affordance, that the link on the Program page should be completely absent unless Indicator Grouping is enabled?

**Comment by jennyhavah** [comment]
@sanjuroj See the newly added #3 underneath the header "Accessing the Logframe web view".

I repurposed some wording from the "old levels" field in the indicator form, and added a bit about the logframe.

**Comment by jennyhavah** [comment]
@sanjuroj Would it be easy or hard to align the question mark icon to the right of the word "logframe" with a single space in between, such that it doesn't wrap onto a new row? Right now it's kinda floaty -- unclear what it's connected to: 

![image](https://user-images.githubusercontent.com/33670923/61086464-bd499600-a3e7-11e9-9809-a965de848958.png)

**Comment by jennyhavah** [comment]
Alignment looks good now!
