### ISSUE TITLE
Custom templates

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1331]
_Note: This is a stretch goal, not a must have._

# Stories
1. **Program team:** I can use results framework terminology in a language Tola doesn't support / that my donor requires, even though it doesn't match any standard templates. 
2. **End user selecting a template:** I don't have to ask the Tola team for a new template to be added, or choose from an ever-growing list of options, none of which are exactly what I need.

# Acceptance criteria

- [x] 0. Custom templates are _**program-specific**_ and a program can only have a single Custom template. Creating a custom template does NOT result in it being added to the template menu so other programs can select it. (This would lead to the exact same proliferation problem we've had with disaggregation types.) 

- [x] 1. When I first load the results framework (RF) builder and open up the template menu, it includes the option "Custom". It should be at the end of the list, set apart from the alphabetized standard templates by some sort of dividing line, like so.

![image](https://user-images.githubusercontent.com/33670923/55361240-71ec2700-548b-11e9-9e69-079abf79f3e1.png)

- [x] 2. If I select the Custom option, the preview area refreshes to display a form like so:

     ![image](https://user-images.githubusercontent.com/33670923/55448172-9d4e3f00-557b-11e9-9571-34eb4cf1e627.png)

     - [x] 2.1. There is a text field with the label "Level 1".
          - [x] 2.1.1. There is a relatively tight character limit. The longest template example I have, translated into French, is "Résultats sous-intermédiaires". Throw in some extra padding and let's say 75.

     - [x] 2.2. Under the text field is an "Add level" button. It is _inactive_ until I type something in the Level 1 text box.

     - [x] 2.3. Similarly, the _Apply_ button is inactive until I type something into the text box.

- [x] 3. After typing something in Level 1, the "Add level" button and Apply buttons both become active. 

- [x] 4. If I click the _Add level_ button, the next level appears -- Level 2 -- like so:

     ![image](https://user-images.githubusercontent.com/33670923/55517031-f376bd00-5623-11e9-81ef-edb10da9d899.png)

     - [x] 4.1. Note that both the _Add next level_ button and _Apply_ buttons are inactive again, until Level 2 has text in it. Whenever a level box is empty, these two buttons are disabled. If you don't want a level after all, delete it. If you're not sure what you want to call a level yet, then put in some placeholder text and edit it later. You just can't have an empty box as a placeholder.

     - [x] 4.2. Let's also put in back end validation to ensure that a Custom template never includes an empty/unnamed level, even if the front end UI fails to inactivate buttons for whatever reason. We can use the standard "Please complete this field" messaging with red text under the empty box/es.

- [x] 5. Up to 6 levels can be added. When you add a 6th level, no _Add level_ button appears under it.

- [x] 6. A level can only be deleted when certain conditions are met:

     ![image](https://user-images.githubusercontent.com/33670923/55517646-f2df2600-5625-11e9-867d-d10bfec6cc23.png)

     - [x] 6.1. It's NOT Level 1. (The top level can never be deleted, only edited.)

     - [x] 6.2. It IS the bottom-most level. (You must delete level 4 before you can delete level 3. You must delete level 3 before you can delete level 2.)

          - [x] 6.2.1. If you delete all levels so that only Level 1 remains, we could display an "X" next to that field, in order to give you a way to clear out the text inside. (This is similar to how you can clear out the top tier RF level form by clicking "Delete".) You just can't delete the actual form field -- similar to how you can't delete the entire Goal form, leaving a blank RF builder.  **Update**: If the first level field has previously been saved and you hit the red "X" button, the field should clear, the value should be deleted from the database, and the red "X" should not be shown until something new has been typed into the text box.

     - [x] 6.3. The level has not yet been used in the results framework

          - [x] 6.3.1. After a level is used in the results framework -- meaning at least one RF level form was filled out and successfully submitted at that level -- we display a "locked" icon to the right of it, where the "X" icon would normally go. Clicking the "locked" icon gives you a tool-tip message: This level is being used in the results framework.

               ![image](https://user-images.githubusercontent.com/33670923/55518039-6897c180-5627-11e9-96be-586438539abc.png)

          - [x]  6.3.2. Again, this might be a good place for back end validation, where if for some reason a delete button shows up when it shouldn't, or someone tries to hack the UI somehow, we block the action and throw the same message: This level is being used in the results framework.

     - [x] 6.4. ~When all the conditions are met, clicking the red "X" button brings up the same type of confirmation prompt we use when you delete an event prior to results being submitted. Message text as follows:~ Decided not to do this because it would be too much warning.

- [x] 7. As long as all level text fields have text in them, I can save by clicking _Apply_. The first time I click _Apply_, ever, for that program, the following things happen.
   
     ![image](https://user-images.githubusercontent.com/33670923/61753507-70a97780-ad64-11e9-86f5-83a312fe597c.png)

     - [x] 7.1. The body of the page reloads with the top level form open -- just as if I'd applied a preset template. 

     - [x] 7.2. The custom template form is replaced by the mini-tree diagram similar to the standardized one. The main difference is that there is a "Settings" button in the lower right corner. Clicking this button switches you back to editing mode. Here's what editing a 6-level template would look like -- after applying the template, but prior to saving the first level:

     ![image](https://user-images.githubusercontent.com/33670923/61753519-78691c00-ad64-11e9-97ef-51d7c94c527c.png)

     - [x] 7.2.1. All RF builder fields and buttons are inactive in the body of the page.
     
     - [x] 7.2.2. All the same button state and deletion rules apply in this state, as when you're first setting up the template -- i.e.  _Apply_ button remains inactive until there are changes ready to apply. You can only delete from the bottom up, etc.

     - [x] 7.2.3. When I make modifications and click _Apply_, I see the updated mini-tree, and I get an auto-dismissing green PNotify confirmation in the lower left corner of the screen: Success! Changes to the results framework template were saved.

     - [x] 7.2.4. If I've changed the text of a level, I see those changes immediately in the saved levels and open forms of the RF builder. <P>

- [x] 8. _(Note: If this criteria will add more than a few hours of work, let's talk about alternative approaches.)_ Just as I can switch between preset templates until I save my first level, I can also switch between Custom and preset templates until I save my first level. When I do this:

     - [x] 8.1. The Custom form is replaced by the preview of levels from whatever template I've selected. 

     - [x] 8.2. The system preserves any Custom levels I've already created, so that I don't have to start all over again if I decide to go back to it.

## Validation

- [x] 1. If I give multiple levels the exact same name, I am prevented from applying the template. I get a warning message that says: Result levels must have unique names. 

- [x] 2. If I use only whitespace for my level name, I should be prevented from saving (i.e. adding a new level or applying the levels) and be given a warning message.

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by sanjuroj** [comment]
@jennyhavah In addition to the warning text you specify in the validation criteria, I'm using the following warning text for whitespace-only text and duplicated whitespace-only text, respectively:
"Result levels must contain at least one letter."
"Result levels must have unique names and contain at least one letter."

Let me know if you want something different.

**Comment by jennyhavah** [comment]
@sanjuroj I'd like to propose we streamline the messaging and use our standard message in both scenarios:

Please complete this field.

(In this case, I don't think we need to be quite so precise. I'm looking at it from the perspective of someone typing too fast and/or accidentally hitting something. From a visual standpoint, for all intents and purposes, the fields are _empty_.)

**Comment by sanjuroj** [comment]
@axoplasm This is finally ready for you, only a week late.  It's not merged into Poblano yet, mainly to give a bit more visibility into the css changes I made.  Let me know if you would prefer to have it merged in and I can do that.  Just a heads up, you'll need to pip install and migrate.

**Comment by jennyhavah** [comment]
@sanjuroj I experienced a strange phenomenon. 

1. I selected Custom.
2. I copied and pasted exactly 75 characters of text from an online character count utility.
3. I clicked "Add level".

Here's what I got:

![image](https://user-images.githubusercontent.com/33670923/62983131-29525c00-bde3-11e9-97a7-087527cc2f5d.png)

As you can see, it added _two_ levels, and the second one is empty. Best I can tell, this happens when I copy and paste text in to the box, which could be fairly common if people are copying text over from a document.

**Comment by jennyhavah** [comment]
@sanjuroj I think we had a small miscommunication about this criteria -- I agreed that we don't need confirmation when deleting, but I didn't expect (and don't recommend) a success message. I found the message surprising and even confusing because I hadn't even applied the template yet.

>  - [x] 6.4. ~When all the conditions are met, clicking the red "X" button brings up the same type of confirmation prompt we use when you delete an event prior to results being submitted. Message text as follows:~ Decided not to do this because it would be too much warning.  User will be prompted that they have successfully updated the template.

**Comment by jennyhavah** [comment]
Pretty sure I saw a success message when I added a level too... _before_ I had applied the template. My intention was that these messages would only appear after you'd applied the template. (That's why I don't mention it until you get to the part of the ticket about what happens after you've applied.)

Basically, if you haven't applied the template yet, you shouldn't be seeing success messages.

**Comment by jennyhavah** [comment]
When I typed into Level 1 and then hit the tab key, it cleared out the form field I'd just typed in. That felt a bit unexpected. Thinking about someone using a screen reader, they wouldn't necessarily know in advance that the next object is a delete button, right? So shouldn't it _select_ the X button but not _click_ it?

**Comment by jennyhavah** [comment]
Another unexpected behavior, this one with the _Return_ key:

1. Type in Level 1.
2. Hit Return -- just to see what would happen. (Similar to seeing what would happen if I tabbed.)

Instead, the result was the same as if I'd clicked "Apply template":

![image](https://user-images.githubusercontent.com/33670923/62983935-0d9c8500-bde6-11e9-811a-6caa82487a26.png)

This was surprising, as I wasn't done and hadn't tabbed over to the Apply button.

My expectation would be that if all I've done is type some text, clicking "Return" shouldn't do anything. If I tab over to "X" and hit Return, it deletes. If I tab over to "Add level" and hit Return, it should add a level.

**Comment by jennyhavah** [comment]
@sanjuroj Based on our earlier conversation, I was expecting that once I apply a custom template -- or any standard template for that matter -- it "sticks". I don't have to save the first level in order for it to "take". It will remember the one I applied.

I think this is particularly important for Custom templates, because I've gone to all of that setup trouble. If I save 6 levels, hit Apply, wander off and come back, it looks as though all of my work is wiped out. It isn't intuitive to me that I have to save my first result level for it to "stick".

**Comment by sanjuroj** [comment]
@jennyhavah Per our conversation, these are the issues that need to be addressed:
1.  Delete doesn't work on first level
2. Special characters interfere with saving a tier name
3. Success messages should only appear when a user clicks apply on a custom template, not every time they delete or add a level.
4. Pressing the enter key should not activate the Apply button.  Ideally, it should do nothing.
5. The tiers should be associated with the program when earlier in the process, when the Apply button is clicked, rather than when the first level is saved.

**Comment by sanjuroj** [comment]
@jennyhavah One follow up question:  I was keeping track of whether or not the custom template has changed, in order to not alert when e.g. the Add level button was clicked but the values of the existing levels hadn't changed.  This helped cut down on what seemed to me to be unnecessary alerts, however, I'm not sure how much it makes sense given that the alerting won't happen as often.  The two opposite scenarios I'm imagining are:

1.  You click the Settings button to edit the template but then change your mind and hit Apply to get back to editing levels.  Getting a save alert might make the user wonder what they did that was worth saving.

2.  A user does a whole bunch of editing but winds up in the same place they were when they started.  Not getting a prompt might make them wonder if the "changes" weren't saved.  

So, any opinion on whether to just prompt whenever they hit apply or to hold off when nothing has changed?

**Comment by sanjuroj** [comment]
@jennyhavah One thing we didn't cover is what happens when someone hits apply (the tiers get saved and the first level card comes up), and then they switch templates.  I'm assuming the new tier set should be saved, even though they are not hitting Apply (because the button is no longer visible).

**Comment by jennyhavah** [comment]
@sanjuroj Once they apply the custom template for the first time, my hope is that we can save the new tiers. At that point -- where they're in selection mode and not edit mode, but have not yet saved their first level -- the Custom template is just like any other standard selection. They can switch between standard and custom, and the preview of tiers appears in either case. The only difference with Custom is that they have the ability to go back into edit mode and change the tiers.

Does that sound ok?

**Comment by jennyhavah** [comment]
@sanjuroj Minor usability request, only if it's easy: Any simple adjustments you could make to the templates menu, such that the Custom option is more likely to be visible without needing to scroll? 

Here's what I see now:

![image](https://user-images.githubusercontent.com/33670923/63229133-05f82a00-c1b2-11e9-846d-13a51bcc7961.png)

**Comment by jennyhavah** [comment]
The Apply button is now always active, as soon as you select Custom and whenever I add a level. As requested in criteria 2.3, it's not supposed to be active while there are incomplete fields.

**Comment by jennyhavah** [comment]
Since the recent update, the very first time I typed some text into the first level and clicked "Add level", I must have double-clicked by accident, as it added two levels instead of one. I'm able to intentionally replicate it as well. I think you mentioned putting in a fix for that, so wondering if it was merged, or if it's maybe just not doing the trick for some reason.

**Comment by jennyhavah** [comment]
Regarding our decision to have the "Return" key not do anything: This is working as expected for the second level on down. But for the very first level, when I hit Return, it is clearing out the text box... basically doing what the Tab key used to do. (It no longer happens when I hit Tab.)

**Comment by sanjuroj** [comment]
This is ridiculous, you should stop testing, it's too buggy.  Let me take another full pass through.

**Comment by jennyhavah** [comment]
@sanjuroj Regarding your last question, to confirm where we landed after our chat: You get a success message when you hit Apply... and that's basically the rule, even if they haven't changed anything, or even if the person winds up in the same place where they started after making edits. 

Is that your understanding as well?

**Comment by sanjuroj** [comment]
@jennyhavah That's right.  And as further clarification, they _don't_ get a success message if they change templates when the level editing mode is open to the first unsaved level card, even though the tiers are being saved to the database in the background if they switch templates.

**Comment by sanjuroj** [comment]
@axoplasm Can you take a look at the spacing weirdness that takes place when custom tier names are long.  See the images below.  The relative size of the picker and levels regions should probably not change depending on what the content of the level names are.

This is a standard template.  
<img width="1426" alt="Screen Shot 2019-08-21 at 6 09 13 PM" src="https://user-images.githubusercontent.com/6685499/63478654-75cf1480-c43f-11e9-8923-f0157cc91cae.png">

This is with custom templates with long level names.
<img width="1429" alt="Screen Shot 2019-08-21 at 6 12 19 PM" src="https://user-images.githubusercontent.com/6685499/63478687-95663d00-c43f-11e9-927f-b154621f1ad9.png">

**Comment by jennyhavah** [comment]
I've tested acceptance criteria on Chrome and Firefox and done some exploratory testing as well. All issues found at this point, I've put in separate tickets. I consider this ticket PASSED.
