### ISSUE TITLE
Deletion rules for indicators

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1370]
# Terminology
**1. Confirmation prompt:** This is a dialogue that warns you of a destructive action and prompts you for confirmation that you want to proceed. 

**2. Rationale prompt:** This is a dialogue that warns you that changes are being logged and prompts you to type text into a rationale field.

# Summary
- We have always had _confirmation prompts_ when you delete just about anything.
- With Partner Access, we've introduced _rationale prompts_ that replace some of the old confirmation prompts. 
- We do NOT require a rationale for every type of deletion.
- However, for any deletion that does NOT require a rationale, _we still need a confirmation prompt._ 
- Some of these confirmation prompts seem to have gone missing, allowing deletions to proceed with no warning. This epic documents expected behaviors for deleting indicators in a variety of scenarios. Other tickets will cover other types of deletions.
- To keep the UX consistent with what's been built for Partner Access, we can apply the same style of notification even when we're only confirming and not prompting for a rationale. 
- Success messages should always appear _after_ the prompt closes, whether it's a confirmation prompt or a rationale prompt.

# Acceptance criteria

## Scenario 1: Delete an indicator that was added without completing the setup process

Because there are no results linked to the indicator, we do not need a rationale for deleting it. However, we still need a confirmation prompt. At the moment, we have problematic behavior captured by Cameron in #1350. Here is the desired behavior:

- [x] 1. I see a red PNotify warning in the lower left corner with the following text:
Warning
This action cannot be undone. All details about this indicator will be permanently removed.
Are you sure you want to delete this indicator?

     ![image](https://user-images.githubusercontent.com/33670923/55847632-e9126280-5afe-11e9-96b0-8475851f3caa.png)

- [x] 2. There are two buttons on this notification: _OK_ and _Cancel_.

- [x] 3.  If I click _Cancel_ or click the "X" in the upper right corner of the notification, it closes and nothing happens.

- [x] 4. If I click _OK_, the following things happen: 
     - [x] 4.1. The indicator is deleted.
     - [x] 4.2. I am returned to the program page.
     - [x] 4.3. In the lower left corner of the program page is a success message with the following text:
     Success
     The indicator was deleted.
     ![image](https://user-images.githubusercontent.com/33670923/55847861-d6e4f400-5aff-11e9-8d69-64201f4a2baf.png) <P>

          - [x] 4.3.1. The success message is auto-dismissing. It does not have an OK button, but does have an "X" button.

- [x] 5. All of the above is true regardless of target frequency of the indicator I've deleted -- time aware, midline/endline, event, LoP-only.

## Scenario 2: Indicator with no results -- regardless of whether or not there are targets in place
As specified in the PA wiki, when there are no results linked to an indicator, we do not need a rationale for deleting the indicator. _However, we still need a confirmation prompt._ Following is the desired behavior if you click "Delete this indicator" on the Summary tab of the indicator setup modal:

- [x] 1. I see a red PNotify warning in the lower left corner _of the indicator setup modal_ (not the screen):
Warning
This action cannot be undone. All details about this indicator will be permanently removed.
Are you sure you want to delete this indicator?
    
     ![image](https://user-images.githubusercontent.com/33670923/55848423-bd44ac00-5b01-11e9-8e4e-0f105f2322c1.png)

- [x] 2. There are two buttons on this notification: _OK_ and _Cancel_.

- [x] 3.  If I click _Cancel_ or click the "X" in the upper right corner of the notification, it closes and nothing happens.

- [x] 4. If I click _OK_, the following things happen: 
     - [x] 4.1. The indicator is deleted.
     - [x] 4.2. The indicator setup modal closes.
     - [x] 4.3. In the lower left corner of _whatever page was behind the modal_, is the following success message:
     Success
     The indicator was deleted.
     
          ![image](https://user-images.githubusercontent.com/33670923/55848548-24faf700-5b02-11e9-8afa-fd563d2a8c11.png)

          - [x] 4.3.1. This is true if I'm coming from the Program page.
          - [x] 4.3.2. This is true if I'm coming from the IPTT.  <P>

     - [x] 4.4. The success message is auto-dismissing. It does not have an OK button, but does have an "X" button.

- [x] 5. All of the above is true regardless of target frequency of the indicator I've deleted -- time aware, midline/endline, event, LoP-only.

## Scenario 3: Indicator with results / with targets
As specified in the PA wiki, when an indicator has results linked to it, we must always prompt for a rationale if you click "Delete this indicator." The interaction details are _mostly_ right. To make it fully consistent with the patterns we're establishing for Satsuma and beyond, it needs some tweaking.
 
- [x] 1. We prompt for a rationale. (This is fine.)
     ![image](https://user-images.githubusercontent.com/33670923/55851012-c9356b80-5b0b-11e9-90d3-3c1e242fd4c8.png)

- [x] 2. The rationale field is required, and I get an error message if I submit without typing anything in. (This is fine.)

- [x] 3. If I type something in and click _OK_, the following should happen, _in the following order._

     - [x] 3.1. The rationale prompt closes.
     - [x] 3.2. In the lower left corner of _whatever page was behind the modal_, is the following success message:
     Success
     The indicator was deleted.
     
          ![image](https://user-images.githubusercontent.com/33670923/55848548-24faf700-5b02-11e9-8afa-fd563d2a8c11.png)

          - [x] 3.2.1. This is true if I'm coming from the Program page.
          - [x] 3.2.2. This is true if I'm coming from the IPTT.  <P>

     - [x] 3.3. The success message is auto-dismissing. It does not have an OK button, but does have an "X" button.

- [x] 4. All of the above is true regardless of target frequency of the indicator I've deleted -- time aware, midline/endline, event, LoP-only.

## Scenario 4: Indicator with results / no targets
This is an edge case that isn't so edgy; it's commonly found in older, pre-Winterhawks programs, and can happen anytime you delete your targets after adding results. Because there ARE results linked to the indicator that will be destroyed, we should absolutely prompt for a rationale and log changes. 

- [x] 1. The prompt/OK/Success message sequence is exactly the same as described in Scenario 3.

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by RickieT** [comment]
**QA - PASSED**

### Scenario 1: Delete an indicator that was added without completing the setup process

- [x] 1. I see a red PNotify warning in the lower left corner with the following text:
Warning
This action cannot be undone. All details about this indicator will be permanently removed.
Are you sure you want to delete this indicator?

     ![image](https://user-images.githubusercontent.com/33670923/55847632-e9126280-5afe-11e9-96b0-8475851f3caa.png)

- [x] 2. There are two buttons on this notification: _OK_ and _Cancel_.

- [x] 3.  If I click _Cancel_ or click the "X" in the upper right corner of the notification, it closes and nothing happens.

- [x] 4. If I click _OK_, the following things happen: 
     - [x] 4.1. The indicator is deleted.
     - [x] 4.2. I am returned to the program page.
     - [x] 4.3. In the lower left corner of the program page is a success message with the following text:
     Success
     The indicator was deleted.
     ![image](https://user-images.githubusercontent.com/33670923/55847861-d6e4f400-5aff-11e9-8d69-64201f4a2baf.png) <P>

          - [x] 4.3.1. The success message is auto-dismissing. It does not have an OK button, but does have an "X" button.

- [x] 5. All of the above is true regardless of target frequency of the indicator I've deleted -- time aware, midline/endline, event, LoP-only.

### Scenario 2: Indicator with no results -- regardless of whether or not there are targets in place

- [x] 1. I see a red PNotify warning in the lower left corner _of the indicator setup modal_ (not the screen):
Warning
This action cannot be undone. All details about this indicator will be permanently removed.
Are you sure you want to delete this indicator?
    
     ![image](https://user-images.githubusercontent.com/33670923/55848423-bd44ac00-5b01-11e9-8e4e-0f105f2322c1.png)

- [x] 2. There are two buttons on this notification: _OK_ and _Cancel_.

- [x] 3.  If I click _Cancel_ or click the "X" in the upper right corner of the notification, it closes and nothing happens.

- [x] 4. If I click _OK_, the following things happen: 
     - [x] 4.1. The indicator is deleted.
     - [x] 4.2. The indicator setup modal closes.
     - [x] 4.3. In the lower left corner of _whatever page was behind the modal_, is the following success message:
     Success
     The indicator was deleted.
     
          ![image](https://user-images.githubusercontent.com/33670923/55848548-24faf700-5b02-11e9-8afa-fd563d2a8c11.png)

          - [x] 4.3.1. This is true if I'm coming from the Program page.
          - [x] 4.3.2. This is true if I'm coming from the IPTT.  <P>

     - [x] 4.4. The success message is auto-dismissing. It does not have an OK button, but does have an "X" button.

- [x] 5. All of the above is true regardless of target frequency of the indicator I've deleted -- time aware, midline/endline, event, LoP-only.

### Scenario 3: Indicator with results / with targets
- [x] 1. We prompt for a rationale. (This is fine.)
     ![image](https://user-images.githubusercontent.com/33670923/55851012-c9356b80-5b0b-11e9-90d3-3c1e242fd4c8.png)

- [x] 2. The rationale field is required, and I get an error message if I submit without typing anything in. (This is fine.)

- [x] 3. If I type something in and click _OK_, the following should happen, _in the following order._

     - [x] 3.1. The rationale prompt closes.
     - [x] 3.2. In the lower left corner of _whatever page was behind the modal_, is the following success message:
     Success
     The indicator was deleted.
     
          ![image](https://user-images.githubusercontent.com/33670923/55848548-24faf700-5b02-11e9-8afa-fd563d2a8c11.png)

          - [x] 3.2.1. This is true if I'm coming from the Program page.
          - [x] 3.2.2. This is true if I'm coming from the IPTT.  <P>

     - [x] 3.3. The success message is auto-dismissing. It does not have an OK button, but does have an "X" button.

- [x] 4. All of the above is true regardless of target frequency of the indicator I've deleted -- time aware, midline/endline, event, LoP-only.

### Scenario 4: Indicator with results / no targets
This is an edge case that isn't so edgy; it's commonly found in older, pre-Winterhawks programs, and can happen anytime you delete your targets after adding results. Because there ARE results linked to the indicator that will be destroyed, we should absolutely prompt for a rationale and log changes. 

- [x] 1. The prompt/OK/Success message sequence is exactly the same as described in Scenario 3.
