### ISSUE TITLE
Deletion rules for targets

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1389]
# Terminology
**1. Confirmation prompt:** This is a dialogue that warns you of a destructive action and prompts you for confirmation that you want to proceed. 

**2. Rationale prompt:** This is a dialogue that warns you that changes are being logged and prompts you to type text into a rationale field.

# Summary
- We have always had _confirmation prompts_ when you delete just about anything.
- With Partner Access, we've introduced _rationale prompts_ that replace some of the old confirmation prompts. 
- We do NOT require a rationale for every type of deletion.
- However, for any deletion that does NOT require a rationale, _we still need a confirmation prompt._ 
- Some of these confirmation prompts seem to have gone missing, allowing deletions to proceed with no warning. This epic documents expected behaviors for deleting targets in a variety of scenarios. Other tickets cover other types of deletions.
- To keep the UX consistent with what's been built for Partner Access, we can apply the same style of notification even when we're only confirming and not prompting for a rationale. 

- **Deleting individual event targets is an action that needs a lot of attention -- it's totally non-functional at the moment.**

# Acceptance criteria

## Scenario 1: Indicator with no targets / no results

As specified in the PA wiki, if results have not yet been associated with the indicator, deletion of the existing targets is NOT logged. However, _we still need a confirmation prompt._ If I complete all required fields, click _Create targets_, and then immediately click _Remove all targets_ before saving the targets, the following things are true:

- [x] 1. I see a red PNotify warning in the lower left corner of the indicator setup form with the following text:

     Warning
     This action cannot be undone. 
     Are you sure you want to remove all targets?

     ![image](https://user-images.githubusercontent.com/33670923/55998819-b8543980-5c74-11e9-948a-3e4f15d1e637.png)

- [x]  2. There are two buttons on this notification: OK and Cancel.

- [x] 3. If I click Cancel or click the "X" in the upper right corner of the notification, it closes and nothing happens.

- [x] 4. If I click OK, the following things happen:

     - [x] 4.1. The notification closes.

     - [x] 4.2. The "Target frequency" menu is reset to "--------".

     - [x] 4.3. We do NOT display a success message in this scenario.

- [x] 5. All of the above is true for all target frequencies except LoP only.

- [x] 6. All of the above is true regardless of whether you're adding a brand new indicator in the full page indicator setup form, or you're using the modal.(In the case of the full page version, "the lower left corner of the form" just means the lower left corner of the page -- as it's not in a modal.)

- [x] 7. All of the above is true regardless of whether you're accessing the modal from the program page or the IPTT.

## Scenario 2: Indicator with saved targets / no results 
As specified in the PA wiki, if results have not yet been associated with the indicator, deletion of the existing targets is NOT logged. However, _we still need a confirmation prompt._ The difference between Scenario 1 and this one, is that in this case you've actually saved the targets.

Following is the desired behavior if you click "Remove all targets" for an indicator that has saved targets but no results. 

- [x] 1. I see a red PNotify warning in the lower left corner of the indicator setup form with the following text:

     Warning
     This action cannot be undone.  
     Are you sure you want to remove all targets?

    ![image](https://user-images.githubusercontent.com/33670923/55998785-98247a80-5c74-11e9-9b6e-d83f65400c71.png)

- [x]  2. There are two buttons on this notification: OK and Cancel.

- [x] 3. If I click Cancel or click the "X" in the upper right corner of the notification, it closes and nothing happens.

- [x] 4. If I click OK, the following things happen:

     - [x] 4.1. The notification closes.

     - [x] 4.2. The "Target frequency" menu is reset to "--------".

     - [x] 4.3. We do NOT display a success message in this scenario.

- [x] 5. All of the above is true for all target frequencies except LoP only.

- [x] 6. All of the above is true whether I'm accessing the modal from the program page or the IPTT.

## Scenario 3: Indicator with saved targets / with results 
As specified in the PA wiki, when an indicator has results linked to it, we must always prompt for a rationale if you click "Remove all targets." The interaction details all look good here. Just capturing here for completeness:
 
1. We prompt for a rationale.

![image](https://user-images.githubusercontent.com/33670923/55995838-71614680-5c6a-11e9-83ea-73f6dbfff333.png)

2. The rationale field is required, and I get an error message if I submit without typing anything in. 

![image](https://user-images.githubusercontent.com/33670923/55995991-f0567f00-5c6a-11e9-8931-798f85d2f2da.png)

3. If I type something in and click OK, the rationale prompt closes and the "Target frequency" menu is reset to "--------". We do NOT display a success message in this scenario.

4. All of this is true whether I'm accessing the modal from the program page or IPTT.

## Scenario 4: Deleting an UNSAVED Event target without results linked to it

Event targets are unique in that they can be manually deleted, one by one. Prior to an event target having results linked to it, we do not prompt at all -- no confirmation, no rationale.

Right now, in the case of an **_unsaved_** event target -- deletion is not working for me on Dev2 the way it is on Production. If I click the red "X" box to the left of the Event target row, I get bounced to the top of the page and the event row just sits there.

### Acceptance criteria
- [x] 1. If there are no linked results, I can delete an **_unsaved_** event target with no confirmation prompt and no rationale prompt.

## Scenario 5: Deleting a SAVED Event target with NO results linked to it.

Again, prior to an event target having results linked to it, we do not prompt at all -- no confirmation, no rationale. In the case of a _**saved**_ event target without results, I get this error page:

![image](https://user-images.githubusercontent.com/33670923/55997447-60670400-5c6f-11e9-871e-cd13864dc673.png)

- [x] 1. If there are no linked results, I can delete a _**saved**_ event target with no confirmation prompt and no rationale prompt.

## Scenario 6: Deleting a SAVED Event target WITH results linked to it.

On Production, we have some pretty sophisticated logic where it checks to see how many results are linked to _each event target._ 

1. If there are no results linked to a specific event, you can delete the target without any confirmation prompt.

2. If there are results linked to a specific event, you see the following confirmation prompt, where it tells you exactly how many results will be affected if you delete the event.

![image](https://user-images.githubusercontent.com/33670923/55997700-4c6fd200-5c70-11e9-90ad-ba1f576e5ae9.png)

Right now on Dev2, I get an error page if I delete an event with results linked to it.

![image](https://user-images.githubusercontent.com/33670923/55997764-7e813400-5c70-11e9-939f-bd6f9373e036.png)

Now, with Partner Access, we are supposed to prompt you for a rationale whenever an indicator has results linked to it. So we need to preserve today's logic and warning message and incorporate a rationale prompt.

### Acceptance criteria
- [x] 1. If I delete an individual event that has one or more results linked to it, I get a rationale prompt with the following text. (Note the variable for quantity of results and the singular or plural of the word "result" depending on whether it's 1 or multiple.)
     Warning
     This action cannot be undone. Removing this target means that [#results] result[s] will no longer have targets associated with it.
     For future reference, please provide a rationale for deleting this target.
     ![image](https://user-images.githubusercontent.com/33670923/55998120-c94f7b80-5c71-11e9-8869-f9400a560227.png)

- [x] 2. If I attempt to submit without typing in text, I get the same error message I get in Scenario 3.

- [x] 3. If I click _Cancel_ or the "X" button, the prompt closes and nothing else happens.

- [x] 4. If I type in the rationale box, the following things happen:

     - [x] 4.1. The prompt closes.
     - [x] 4.2. The event is deleted.
     - [x] 4.3. We do NOT display any success message.
     - [x] 4.4. The deletion action and rationale are logged in the change log.

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by jennyhavah** [comment]
@hannalcamp Tagging you so that you can review and let us know if you have any questions or concerns, or have any Parthenon historical context to share.

In particular, please check out the gaps around event deletion -- just in case it requires any updates to documentation, training materials, etc.

**Comment by jennyhavah** [comment]
Accidentally closed the ticket instead of opening it... Because I'm talented like that.

**Comment by esinn** [comment]
@camgnostic When I try to delete an Event target without existing results linked I get the following screen 
![image](https://user-images.githubusercontent.com/13574772/56178022-8107c480-5fb5-11e9-9c3c-f0a153ddfeee.png)

**Comment by RickieT** [comment]
**QA - FAILED**
* The message displayed when attempting to remove an event with linked evidence does not meet the required message in the criteria for this ticket, which should read: "Warning
This action cannot be undone. Removing this target means that [#results] result[s] will no longer have targets associated with it.
For future reference, please provide a rationale for deleting this target."
![Screen Shot 2019-04-16 at 1 34 47 PM](https://user-images.githubusercontent.com/23220180/56242127-69c7e600-604c-11e9-979f-f88a73963e70.png)

**Comment by camgnostic** [comment]
That's what I'm seeing on dev2 (screenshot attached) . Are you positive in your test case you had results attached?  Can you give me a step-by-step recreate so I can find the edge case you bumped into?  
![Screen Shot 2019-04-16 at 2 22 34 PM](https://user-images.githubusercontent.com/7941355/56244984-1f963300-6053-11e9-84d9-10c8d8ff9985.png)

**Comment by RickieT** [comment]
**QA - PASSED**
* Scenario 6 is now passing, additionally, with the rest of the scenarios in this ticket. Moving to deploy ready
![Screen Shot 2019-04-16 at 2 26 05 PM](https://user-images.githubusercontent.com/23220180/56245199-a814d380-6053-11e9-82bd-a9a7357600c3.png)
