### ISSUE TITLE
Indicator setup form: Do not prompt for a rationale all the damn time

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1427]
This work is split off #1412.

**Affects:** Indicator setup form

# Issue
When an indicator has linked results, we are currently prompting for rationales any time you click the "Save changes" button... not only when you change the specific fields we're actually tracking. It even prompts for a rationale if you've changed _nothing at all!_ 

# Acceptance criteria

- [x] 1. For an indicator **_with linked results_**, clicking "Save changes" on the indicator setup form only prompts you for a rationale when: 

     - [x] 1.1. You've made a change to _tracked fields_. This includes indicator name, baseline, unit of measure, LoP target, and target periods fields. (Remember that event targets have an extra field -- the event name.)

     - [x] 1.2. You're deleting targets. (See #1389 and #1424 for complex logic around these prompts. We need to be careful not to regress any of that.)

     - [x] 1.3. You're deleting the indicator. (See #1370 for complex logic around deleting indicators -- we need to be careful not to regress any of that.)

- [x] 2. I am NOT prompted for a rationale when I make changes to untracked fields.

- [x] 3. Potential edge case: I am NOT prompted for a rationale if I click "Save changes" without making any changes.

- [x] 3. _Tracked changes_ continue to show up in the change log along with their rationales.

- [x] 4. For indicators WITHOUT linked results, we continue logging some changes WITHOUT requiring a rationale. These are listed in #1382. (I believe we're already logging these, with a temporarily generic message in the Rationale column.)

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by jennyhavah** [comment]
@hannalcamp Can you please review and let me know if this looks good to you? In particular, my suggestion that we continue logging changes to other fields, with explanatory text when a rationale is not required... and then the wording of that text.

**Comment by hannalcamp** [comment]
@jennyhavah It mostly looks good to me, though if it turns out we actually can delineate between changes to individual fields when the button is clicked, shouldn't we also disregard changes to the "Rationale for target" field in the Targets tab, as it is not required?

I think 1382 provides all the explanatory text we need at the moment, correct?

**Comment by jennyhavah** [comment]
> jennyhavah It mostly looks good to me, though if it turns out we actually can delineate between changes to individual fields when the button is clicked, shouldn't we also disregard changes to the "Rationale for target" field in the Targets tab, as it is not required?

Good point. Asking for a rationale for changing the rationale seems a bit trippy. Updated.

> I think 1382 provides all the explanatory text we need at the moment, correct?

@hannalcamp What if an indicator has linked results and they modify one of the fields we are not prompting for? 1382 only deals with whether or not there are linked results.

**Comment by hannalcamp** [comment]
Right! I'll update #1382

**Comment by jennyhavah** [comment]
@hannalcamp So, regarding this piece that was previously in the ticket:

> 2. We continue to log changes to other indicator fields. But if it is a field that does NOT require a rationale, then we put some text in the Rationale column of the change log, consistent with what we're doing in #1382: A rationale is not required when altering details that are unrelated to an indicator's phrasing or targets.~ This is actually a lot of extra work.

I was originally under the impression that it would be easier to log _all the things_ and just limit when you get prompted. That turned out not to be the case.  Logging _all the things_ is actually a substantial amount of extra work, independent of whether or not we prompt for rationales. Since it was never a goal of ours to log everything, and we actually preferred to be more selective... I took it out.

**Comment by hannalcamp** [comment]
@jennyhavah that seems fine to me. I had also assumed logging all the things would be an easier resolution to the rationales-prompted-but-not-displayed issue than limiting rationale prompts. If the latter is easier, that's good

**Comment by hannalcamp** [comment]
@KennyMonster I know it's minor, but could we exclude the "Rationale for Targets" field from being prompted/tracked? Since it's not required it seems strange to change

**Comment by KennyMonster** [comment]
@hannalcamp Done!

**Comment by jennyhavah** [comment]
@KennyMonster I just tried adding a rationale for target to two different indicator. I was not prompted for a rationale, but I got an error message upon submit:

![image](https://user-images.githubusercontent.com/33670923/56450032-837c5e00-62d6-11e9-9bd3-c4e095167ca1.png)

**Comment by KennyMonster** [comment]
@jennyhavah What was the exact change made that resulted in no rationale prompt? Was it a change in value of one of the periodic targets or something else?

**Comment by KennyMonster** [comment]
The issue above was being caused by trailing whitespace in the program name of programs generated by the QA script. I changed the comparison check to strip out leading and trailing whitespace of text fields to avoid this case in the future.

**Comment by jennyhavah** [comment]
PASSED. Tested on a couple of QA indicators, and it looks good. Everything else related to rationale prompting and logging was tested as part of #1412.
