### ISSUE TITLE
Django auth flow

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1443]
Django login and related auth flows need love. This will mean rewriting the views for the password reset page and allowing users to log in with their email address.

Before we tackle the following tickets I want to map out the user flows. Ken summarized them with:

> Password reset workflow is a whole thing though, and wanted to verify that the stock Django workflow is desired and worth the time investment. From memory, I think the workflow is:
>
> * user clicks link that they forgot their password
> * they are taken to a form where they type in their email
> * user is sent to a page saying an email is sent (or something went wrong)
> * an email is sent to the user containing a link to a page where they enter in a new password
> * the user clicks the link, types in their PW twice, and submits
> * a success page is shown saying the reset succeeded

#### Related tickets:

- [x] #1411 Use email instead of username to log in
- [x] #1342 Meaningful error messages for Django log in page
- [x] #1425 Password reset link 
- [x] #1378 Password security rules
- [x] Reimplement Registration email (I removed this functionality with Parthenon’s earlier attempt)

**Comment by axoplasm** [comment]
Here’s what I have running on my local:

> * user clicks link that they forgot their password

![image](https://user-images.githubusercontent.com/169060/56473604-7d939380-6422-11e9-82ea-e3d2a49e6f46.png)

> * they are taken to a form where they type in their email

![image](https://user-images.githubusercontent.com/169060/56473616-af0c5f00-6422-11e9-8722-f83470d35ceb.png)

> * user is sent to a page saying an email is sent (or something went wrong)

![image](https://user-images.githubusercontent.com/169060/56473621-b9c6f400-6422-11e9-92dc-e2b0ec7784b7.png)

> * an email is sent to the user containing a link to a page where they enter in a new password

```
Someone has requested that you change the password associated with the username pjs on the Mercy Corps Tola Activity application. This usually happens when you click the “forgot password” link.

If you did not request a new password, you can ignore this email.

If you want to change your password, please click the following link and choose a new password:


http://mercycorps.org/auth/reset/MTEwMA/55o-2a3b5edf8706210457e0/


You can also copy and paste this link into the address bar of your web browser.

Thank you,
The Mercy Corps team
```

*(I am sending email output to my terminal locally, this will be a plain text email otherwise. Also note the domain is wrong, I need to get this sorted.)*

> * the user clicks the link, types in their PW twice, and submits

![image](https://user-images.githubusercontent.com/169060/56473653-17f3d700-6423-11e9-9272-578941ac7da0.png)

*(Note multiple error messages handled automatically!)*

> * a success page is shown saying the reset succeeded

![image](https://user-images.githubusercontent.com/169060/56473668-3659d280-6423-11e9-8d8e-1890aaf1638f.png)

Incidental to this solution I’ve updated the email that gets sent when we register new users (or “resend registration email”):

```
A user account was created for you on Mercy Corps' Tola Activity application.  Your username is: pjs

If you are using a mercycorps.org email address to access Tola Activity, you use the same Okta login that you use for other Mercy Corps websites.

If you are using a Gmail account to access Tola Activity, please use this link to connect your Gmail account:

http://127.0.0.1:8000/login/google-oauth2/

If you are using another email account, please use this link to choose a new password:

http://127.0.0.1:8000/auth/reset/MTEwMA/55o-d232b3fc7d7c7899bd79/


Thank you,
The Mercy Corps team
```

We could probably test the user’s email to customize this message.

**Comment by axoplasm** [comment]
See also my partial solution to #1411, where I explicate the username field in Admin Lite and to end users (for example in the reset email above)

**Comment by axoplasm** [comment]
Small note, I updated the urls for this flow. I was using `/auth/[path]` which worked OK but to keep them in line with our expected redirects (see [all these failed tests](https://travis-ci.org/mercycorps/TolaActivity/builds/522779565?utm_source=github_status&utm_medium=notification) I changed them to `/accounts/[path]`

Personally I __hate__ the `/accounts/` path, although I can’t pinpoint why exactly.

**Comment by RickieT** [comment]
**QA - PASSED**
* As a result of the following tickets below passing QA testing, this ticket is validated by such:
- [x] #1411 Use email instead of username to log in
- [x] #1342 Meaningful error messages for Django log in page
- [x] #1425 Password reset link 
- [x] #1378 Password security rules
- [x] Reimplement Registration email (I removed this functionality with Parthenon’s earlier attempt)
