### ISSUE TITLE
Change log: Missing previous / next entry details for disaggregated values and sites, unnecessarily prompting for changes to Comments

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1481]
I found a bunch of issues with the results form -- Figured I'd collect them in an epic.

# Acceptance criteria

## Result form

- [x] 1. I am NOT prompted for a rationale when I change the Comments field.
- [x] 2. I am NOT prompted for a rationale when I change the Project field. (Edge case, only applies to countries with access to Projects.)

### Actual value
- [x] 1. Decimals are consistently in the Previous and New columns -- applying whatever rules we apply in the IPTT and program page. At the moment, they're handled differently. Check it out:

     ![image](https://user-images.githubusercontent.com/33670923/56701101-68cd2f00-66b2-11e9-9d29-4e5bf9ffcded.png)

## Disaggregated values
- [x] 1. If I make changes to disaggregated data values, those changes are captured in the change log. 

- [ ] ~2. I ONLY see the Previous entry / Next entry values for any disaggregation categories that were changed.~ moved to #1520

- [ ] ~3. Do NOT display the actual value in Previous/New columns, unless it actually changed. (Right now that's all you see... even when it's not the field that changed.)~ Moved to #1520

### Sites
We need to actually track changes to this field. (At the moment, we prompt for a rationale and add a row to the change log, but do not display the changed values in the log.)

- [x] 1. Do NOT display the actual value in Previous/New columns, unless it actually changed. (Right now we display it when the _site_ changed.)

- [x] 2. DO display the site values that changed.

### Comments
- [x] 1. I do NOT see a change log row when the comment field changes, because we're not tracking this field. (Currently we display a row with no useful information.)

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [x]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by jennyhavah** [comment]
@hannalcamp Just a heads up. Given that we are about to do extensive work on disaggregations as part of Goat Tree, my inclination is to defer this. But let us know if you consider it a release blocker.

Also, please let me know if you agree with acceptance criteria number 2. My assumption is that it's not useful to list every single disaggregation category -- only the ones that were changed. But you may have a different perspective.

**Comment by hannalcamp** [comment]
@jennyhavah Agreed with both deferring and Criteria Number 2

**Comment by jennyhavah** [comment]
@hannalcamp This ticket turned into a bit of an epic. A few more things I want to validate:

1. Do we want to log changes to sites? If not, we shouldn't prompt for a rationale. (If yes, we should capture the values.)

2. Do we want to log changes to Comments? (Same deal -- either we shouldn't prompt, or we should capture the changes in the log.)

**Comment by hannalcamp** [comment]
@jennyhavah If we don't log changes to sites, and someone modifies the Site in a result, does that change still get displayed in the log? I assume so.

If yes, then I'm in favor of not logging changes to sites, as only high-level users will be allowed to delete sites.

As for 2., is this Comments in the indicator form? If yes, then let's not track it.

**Comment by jennyhavah** [comment]
> @jennyhavah If we don't log changes to sites, and someone modifies the Site in a result, does that change still get displayed in the log? I assume so.

@hannalcamp I should clarify: I'm not talking about logging whether sites are added or deleted to the program. I'm talking about changes to a **result** -- where a site is linked to the result, and the modified. Like "Oh, this value previously was linked to Village A and now it's Village B." Should we be logging _that_ type of change? Right now you essentially get an empty row with the rationale. You can't see what the site was before or after. I'm inclined to track it, but let me know what you think. 

Comments are also in the result form. It doesn't make sense to me to prompt for a rationale for a comment... But do you think we should be logging _changes_ to comments? I lean towards no, but let me know what you think.

**Comment by hannalcamp** [comment]
Ah yes, I see what you mean now. Yes, if the site of the result is changed, we should track it.

I also lean towards no tracking of changes to comments.

**Comment by jennyhavah** [comment]
@hannalcamp Ticket updated, and Ken is working on it.

**Comment by RickieT** [comment]
### QA Failed:

* Change log displays decimals for both values in | Previous | New Entry | columns when value is even (without deliberate decimal entries manual from user), we display decimals in other places, and that is fine, after talking with @jennyhavah we don't want to show ".00" in the change log, when the value is even. If the user enters a value such as 20.35, then I would expect to see that value as such in the change log with decimal (as we currently already do):
![Screen Shot 2019-04-29 at 9 22 21 AM](https://user-images.githubusercontent.com/23220180/56911593-2153f380-6a62-11e9-80b9-f4ddc3b01d5b.png)

**Comment by KennyMonster** [comment]
This has been changed such that future log entries will hide the decimal and zeros if a whole number.

**Comment by RickieT** [comment]
### QA Failed: 
* I ONLY see the Previous entry / Next entry values for any disaggregation categories that were changed. **( we see values 'n/a' of entries we did not edit )**

* Do NOT display the actual value in Previous/New columns, unless it actually changed. (Right now that's all you see... even when it's not the field that changed.)
![Screen Shot 2019-04-29 at 11 45 58 AM](https://user-images.githubusercontent.com/23220180/56919182-d5f71080-6a74-11e9-9468-47c089c4f7ec.png)

**Comment by KennyMonster** [comment]
@RickieT The N/A -> empty string above is the result of an existing implementation detail of how we store disaggregation values. Basically we store nothing, until 1 value is added, at which point we create entries for every possible desegregation value in the form.

In the above example, the N/A entry on the left represents non-existence, where the right represents existence with an empty string value that exists in the DB. From an annoyingly pedantic standpoint, it *did* change.

Granted, it's not ideal, but not something that should be tackled IMO if trying to push out the door tomorrow.

**Comment by RickieT** [comment]
@jennyhavah whats your opinion here, the criteria is passing in this ticket other than the issues described above. You wanna separate this criteria and defer it for post release?

**Comment by jennyhavah** [comment]
@RickieT I field ticket #1520 regarding the display of disaggregated values and put it in the "baby goat" column of Poblano.

I also crossed out two of the acceptance criteria in the original ticket, where those criteria are now in 1520.

**Comment by RickieT** [comment]
### QA Passed:
* As a result of splitting criteria, this ticket now is passing QA.
* Comments and projects field changes:
![pass_commentpro](https://user-images.githubusercontent.com/23220180/56921688-47d25880-6a7b-11e9-8100-7ca27ea1bec5.gif)
* Whole values do not have the ".00" displayed anymore:
![Screen Shot 2019-04-29 at 11 41 29 AM](https://user-images.githubusercontent.com/23220180/56921747-705a5280-6a7b-11e9-9ebb-bad8a5e9ea4d.png)
* Sites is logging properly:
![Screen Shot 2019-04-29 at 12 37 20 PM](https://user-images.githubusercontent.com/23220180/56921804-8d8f2100-6a7b-11e9-9575-0db509aa191f.png)
