### ISSUE TITLE
Users > Programs and Roles: Usability issues

### ISSUE THREAD

**Issue by hannalcamp** [mercycorps/TolaActivity#1501]
Reference for different issues relating to the Programs and Roles tab of the User profile in the Tola Admin UI.

- [ ] #1404 Give Super admins "Basic Admin" access to all countries

- [ ] #1532 Super admins: When editing Programs and Roles for a non-MC user, disable Country level role menus

- [ ] #1377 Selected/unselected checkboxes are nearly indistinguishable

- [ ] #1494 Change "User" to something more 
descriptive of whole-country access

- [ ] #1500 Make it easier to tell who has program access and how to give it to them

**Comment by jennyhavah** [comment]
This epic duplicates other tickets, not useful for prioritization. It also includes some tickets that are done.
