### ISSUE TITLE
Results Framework Builder — Styling & layout

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1566]
Catchall epic for styling RF Builder. I’m building this ticket in reverse, please add screens or components to style as links to the epic below:

- [x] #1567: RF Builder Level Tier picker
- [x] #1569: RF Builder title
- [x] #1570: RF Builder level (empty)
- [x] #1571: RF Builder Level (collapsed)
- [x] #1572: RF Builder Level (expanded/with form)

**Comment by sanjuroj** [comment]
@axoplasm Couple of things I noticed while messing around with the builder:

The title area can get a little weird looking when the program name is long.  From the image below, you can imagine if the title was a bit longer, the Results framework title and logo would get pushed far to the right and possibly wrap.  I think it looks sort of odd that way but 🤷‍♂ .  
![image](https://user-images.githubusercontent.com/6685499/58672356-65eddb80-82fb-11e9-9b12-8b5a90fc40db.png)

The other thing is that when the button text is long, the buttons start looking pretty weird.
![image](https://user-images.githubusercontent.com/6685499/58672341-5cfd0a00-82fb-11e9-9330-a1b61ad482fb.png)

**Comment by axoplasm** [comment]
The buttons are kind of an Issue. We need to rethink our buttons generally. I spiked them in #1610
