### ISSUE TITLE
Light the Create Targets button on fire

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1581]
# Issue
🔥the Create Targets button in order to reduce the number of states possible in the course of target creation, with a number of cascading UX benefits:

1. Streamline the process for users -- no intermediate "Create targets" step.
2. Integrate LoP target into the targets table and _automatically generate_ the LoP value based on targets entered and indicator type (cumul/non-cumul). Prevent errors, woo!
3. Make the process of deleting all targets consistent across target frequencies, including LoP-only.

# Acceptance criteria

## Scenario 1: Targets tab empty state

**Precondition:** I'm in the process of adding a new indicator, and have not yet saved it. 

![image](https://user-images.githubusercontent.com/33670923/58133111-e31ca080-7bd7-11e9-8f27-b217057ffdc7.png)

- [x] 1. The LoP target field no longer appears in the top section of the form. 

- [x] 2. The "Direction of change" menu is moved in between the Baseline and Target frequency fields. That way the menu still has some context; you're logically moving from "What's your baseline?" to "What direction do you want to move from the baseline?"

## Scenario 2: Select time-aware or Midline and Endline target frequency

![image](https://user-images.githubusercontent.com/33670923/58135525-ba000e00-7bdf-11e9-83b6-fb210111f096.png)

As soon as I select Midline/endline, Annual, Semi-annual, Tri-annual, Quarterly, or Monthly, the following things happen:

- [x] 1. The target frequency menu is no longer editable, but I can still see all of the options.

- [x] 2. The periodic targets table is immediately generated with correct period names and date ranges.

- [x] 3. % signs show up in the target value fields when the UoM is toggled to %. (This feature seems to be regression-prone, so just flagging.)

- [x] 4. The Life of Program (LoP) row is now _auto-generated_. The rules are as follows:

     - [x] 4.1. Non-cumulative number indicator: The LoP value is the sum of periodic target values. It's the exact same thing as the Sum row -- we're just relabeling it "Life of Program (LoP) target"

          - [x] 4.1.1. The Sum row is gone, because it's redundant.

          - [x] 4.1.2. As is the case today with the Sum row, the LoP value updates as you enter and edit periodic targets. You don't have to wait until submitting the form to see what the LoP value is.

     - [x] 4.2. Cumulative number or percentage indicator: The LoP value is identical to the final periodic target value.

          - [x] 4.2.1 The LoP value updates as soon as you enter or edit the final periodic target. You don't have to wait until submitting the form to see what the LoP value is.

- [x] 5. The "Remove all targets" button is positioned below the targets table on the right side. 

     - [x] 5.1. Prior to saving the indicator and prior to results being linked, all confirmation dialogues (no rationale) appear as they do on Production.

     - [x] 5.2. After results are linked, all target-related rationale prompts appear as they do on Production, and changes are logged as expected.

## Scenario 3: Select LoP only target frequency

Note: If we decide NOT to do Scenario 1 for Satsuma, then we need to make some refinements to this section. Because it would be odd to have the same field appearing twice.

![image](https://user-images.githubusercontent.com/33670923/58135408-32b29a80-7bdf-11e9-8135-aa52b22387fb.png)

As soon as I select "Life of Program (LoP) only" as my target frequency, the following things happen.

- [x] 1. The target frequency menu is no longer editable, but I can still see all of the options.

- [x] 2. NEW: A target table is generated, just like all the other frequencies.

     - [x] 2.1. The table title is Life of Program (LoP) target

     - [x] 2.2. The table has a single Life of Program (LoP) row with the same styling we use for other target frequencies. The difference is that you have to manually enter the target value, since it's the one and only target and can't be auto-generated.

          - [x] 2.2.1. A % sign appears in this field if you toggle from # to % under Unit of Measure, just like with periodic targets.

     - [x] 2.3. There is a "Remove target" button positioned below the targets table on the right side. (Note the singular "target" instead of "all targets".

     - [x] 2.4. The "Remove target" button is functionally equivalent to the "Remove all targets" button in terms of the confirmation prompts and rationale prompts that appear depending on whether or not the indicator is saved and whether or not it has linked results.

## Scenario 4: Select Event target frequency

![image](https://user-images.githubusercontent.com/33670923/58137470-3ea25a80-7be7-11e9-8ddd-88249dba3be6.png)

As soon as I select "Event" as my target frequency, the following things happen.

- [x] 1. The target frequency menu is no longer editable, but I can still see all of the options.

- [x] 2. The periodic targets table is immediately generated with a single empty event row.

- [x] 3. % signs show up in the target value fields when the UoM is toggled to %. (This feature seems to be regression-prone, so just flagging.)

- [x] 4. The Life of Program (LoP) row is _auto-generated_ according to the rules described in Scenario 2.

- [x] 5. The "Add event" button is left-aligned instead of right-aligned. (This is actually consistent with Paul's recent list UIs in the Admin section.)

- [x] 6. The "Remove all targets" button is positioned below the targets table on the right side. 

     - [x] 6.1. Prior to saving the indicator and prior to results being linked, all confirmation dialogues (no rationale) appear as they do on Production.

     - [x] 6.2. After results are linked, all target-related rationale prompts appear as they do on Production, and changes are logged as expected.

     - [x] 6.3. Confirmation and rationale prompts work as they do on Production when you delete individual targets.

## Scenario 5: There is a manually entered LoP value and no periodic targets

The form will already be displaying a warning message about incomplete targets, like so:
![image](https://user-images.githubusercontent.com/33670923/58669606-a3e60200-82f1-11e9-9a09-38d4dc88785b.png)

- [x] 1. After "Please complete all required fields in the Targets tab." add another line: 

     This program previously had a LoP target of [value]. Life of Program (LoP) targets are now automatically displayed.

     - [x] 1.1. If it's a percentage LoP, we include the percent sign in the message. <P>

- [x] 2. After I successfully save the form, this message goes away. 

## Scenario 6: There are periodic targets and a manually entered LoP value that matches what we're automatically displaying

- [x] Yay! No need to display a warning message.

## Scenario 7: There are periodic targets and a manually entered LoP value that does NOT match what we're automatically displaying

- [x] 1. Display a red box warning message at the top of the form that says: 

     Life of Program (LoP) targets are now automatically displayed. The current LoP target does not match what was manually entered in the past -- [value]. You may need to update your target values.

     - [x] 1.1. If it's a percentage LoP, we include the percent sign in the message. <P>

- [x] 2. After I successfully save the form, this message goes away. 

## Housekeeping
* [x]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by jennyhavah** [comment]
From Slack:

![image](https://user-images.githubusercontent.com/33670923/58069662-fafa1300-7b4a-11e9-9f97-93a99ecbe8f1.png)

**Comment by jennyhavah** [comment]
@KennyMonster I wrote the following based on our chat yesterday. If this looks good to you, feel free to copy and paste it directly into the ticket. 

## Scenario 5: There is a manually entered LoP value and no periodic targets

The form will already be displaying a warning message about incomplete targets, like so:
![image](https://user-images.githubusercontent.com/33670923/58669606-a3e60200-82f1-11e9-9a09-38d4dc88785b.png)

- [ ] 1. After "Please complete all required fields in the Targets tab." add another line: 

     This program previously had a LoP target of [value]. Life of Program (LoP) targets are now automatically displayed.

     - [ ] 1.1. If it's a percentage LoP, we include the percent sign in the message.

- [ ] 2. After I successfully save the form, this message goes away. 

## Scenario 6: There are periodic targets and a manually entered LoP value that matches what we're automatically displaying

- [ ] Yay! No need to display a warning message.

## Scenario 7: There are periodic targets and a manually entered LoP value that does NOT match what we're automatically displaying

- [ ] 1. Display a red box warning message at the top of the form that says: 

     Life of Program (LoP) targets are now automatically displayed. The current LoP target does not match what was manually entered in the past -- [value]. You may need to update your target values.

     - [ ] 1.1. If it's a percentage LoP, we include the percent sign in the message.

- [ ] 2. After I successfully save the form, this message goes away.

**Comment by jennyhavah** [comment]
Regarding Scenario 5: Something I did not consider... What if the target frequency is LoP-only? Thi is what I'm seeing:

![image](https://user-images.githubusercontent.com/33670923/59398451-22f12680-8d45-11e9-8f50-fc203031aab3.png)

So... Unclear what to do next, right? In this case, can we auto-generate the new type of LoP target table, and just fill in the original number, no error message required?

**Comment by jennyhavah** [comment]
On QA Jenny, I'm seeing some LoP only indicators with an extra LOP row, like so:

![image](https://user-images.githubusercontent.com/33670923/59398723-0f928b00-8d46-11e9-978b-dc2e3e9bb48f.png)

So far I can't reproduce the problem when I add a new indicator or edit an existing indicator for a program using the results framework. And I don't see it in older programs using the old levels.

**Comment by KennyMonster** [comment]
I was able to reproduce the case where LoP target period is showing up twice. I haven't figured out the exact steps yet, but I'm looking into it.

As for this case, is there an indicator on QA that I can click to see this in action? https://github.com/mercycorps/TolaActivity/issues/1581#issuecomment-501520426

**Comment by KennyMonster** [comment]
The problem with 2 LoP target periods being created is something that is limited only to QA programs, due to how they are created being different than the normal codepath. Regardless, I made a change such that it shouldn't be a problem going forward. The change is in 7b937fc2b3fc09e164640b7d4d9c6385581171fe

The QA programs on the QA server will continue to be broken unless you change the target frequency to something other than LoP only, and then change it back.

**Comment by KennyMonster** [comment]
Regarding the weird form state found in https://github.com/mercycorps/TolaActivity/issues/1581#issuecomment-501520426

For whatever reason, there are indicators that get into a state where

* The target frequency is set to something (in this case LoP only)
* There are no periodic targets associated with the indicator. Even in the case of LoP only, there should be 1 dummy PT

The only time there should be 0 PTs is when the target frequency is set to nothing.

Below are a list of Indicators that are in this weird state currently:

```
Resilient Communities Program (RCP)  |  Mongolia  |  Perceived Stress Scale
33217 - Fish for School Feeding Initiative (LDS Charities)  |  Timor Leste  |  % of fish farmers are supported to improve their fish production and productivity through increased access to and adoption of improved fish farming techniques and technologies
[DRC_33273] REACH 3  |  Democratic Republic of the Congo  |  [DRC_33273] 1.1.2 Percent of water points developed, repaired, or rehabilitated that are clean and protected from contamination
[DRC_33273] REACH 3  |  Democratic Republic of the Congo  |  [DRC_33273] 1.1.4 Percent of people who feel safe at water collection points
[DRC_33273] REACH 3  |  Democratic Republic of the Congo  |  [DRC_33273] 1.2.1 Number of people directly utilizing improved sanitation services provided with OFDA funding
[DRC_33273] REACH 3  |  Democratic Republic of the Congo  |  [DRC_33273] 1.2.2 Proportion of men, women, boys and girls who last defecated in a toilet (or whose feces was last disposed of in a safe manner)
[DRC_33273] REACH 3  |  Democratic Republic of the Congo  |  [DRC_33273] 1.2.3 Percent of latrines/defecation sites in the target population with handwashing facilities that are functional and in use
[DRC_33273] REACH 3  |  Democratic Republic of the Congo  |  [DRC_33273] 1.2.4 Percent of households targeted by the sanitation program with access to clean latrines
[DRC_33273] REACH 3  |  Democratic Republic of the Congo  |  [DRC_33273] 1.3.1 Number of people receiving direct hygiene promotion (excluding mass media campaigns and without double-counting)
[DRC_33273] REACH 3  |  Democratic Republic of the Congo  |  [DRC_33273] 1.3.2 Percent of households targeted by the hygiene promotion program who store their drinking water safely in clean containers
[DRC_33273] REACH 3  |  Democratic Republic of the Congo  |  [DRC_33273] 1.3.3 Percent of people targeted by the hygiene promotion program who know at least three (3) of the five (5) critical times to wash hands
[DRC_33273] REACH 3  |  Democratic Republic of the Congo  |  [DRC_33273] 1.3.4 Percent of children under five (5) years with diarrhea in the past two weeks
[DRC_33273] REACH 3  |  Democratic Republic of the Congo  |  [DRC_33273] 1.4.1 Total number of people receiving WASH NFIs assistance through all modalities (Without double-counting)
[DRC_33273] REACH 3  |  Democratic Republic of the Congo  |  [DRC_33273] 1.4.2 Percent of households reporting satisfaction with the contents of the WASH NFIs received through direct distribution (i.e. kits) or vouchers
[DRC_33273] REACH 3  |  Democratic Republic of the Congo  |  [DRC_33273] 1.4.3 Percent of households reporting satisfaction with the quality of WASH NFIs received through direct distribution
[DRC_33273] REACH 3  |  Democratic Republic of the Congo  |  [DRC_33273] 1.4.4 Percent of people targeted by the WASH NFI program who report feeling safe during the NFI distribution fair
[DRC_33273] REACH 3  |  Democratic Republic of the Congo  |  [DRC_33273] 2.0.1 Number of people participating in CFW activities
Desarrollo Rural Inclusivo - Alternative Livelihoods for Coca Growers (ALGO Nuevo)  |  Colombia  |  Número de productores agrícolas que sustituyen ingresos provenientes de cultivos de uso ilícito por cultivos lícitos.
Somalia Youth Leaders Initiative (SYLI)  |  Somalia  |  Number of girl-friendly spaces constructed and equipped
Somalia Youth Leaders Initiative (SYLI)  |  Somalia  |  Number of women council for girls education established
RECOVER 2  |  Niger  |  Number of advanced assessment for water points situation
Empowering Sustainable Communities in Gaza - WASH  |  Palestine  |  Constructed and functioning water desalination plant
Empowering Sustainable Communities in Gaza - WASH  |  Palestine  |  Amount in cubic meter of clean drinking water produced by the desalination plant over one year
Empowering Sustainable Communities in Gaza - WASH  |  Palestine  |  No of households reached through water use awareness campaign
Empowering Sustainable Communities in Gaza - WASH  |  Palestine  |  % of people reporting enhanced access to clean drinking water as a result of the program.
Empowering Sustainable Communities in Gaza - WASH  |  Palestine  |  Distance between farthest targeted beneficiary household and the nearest water collection point
Empowering Sustainable Communities in Gaza - WASH  |  Palestine  |  Total number of brackish water desalination plants receiving assistance to improve the quality of the drinking water they produce.
Empowering Sustainable Communities in Gaza - WASH  |  Palestine  |  Total number of men, women, and children educated about safe drinking water as a result of the public awareness campaign
Empowering Sustainable Communities in Gaza - WASH  |  Palestine  |  Total amount of water quality improved in Khan Younis, produced and distributed by the private sector over a year
TolaData Test  |  United States  |  event indicator with just one event
Promoting Agriculture, Health and Alternative Livelihoods (PAHAL)  |  Nepal  |  Percentage of adults who can name two sources of vitamin A rich foods
Promoting Agriculture, Health and Alternative Livelihoods (PAHAL)  |  Nepal  |  Yield of targeted agricultural commodities among program participants with USG assistance.
Promoting Agriculture, Health and Alternative Livelihoods (PAHAL)  |  Nepal  |  Percentage of  households which feel confident in the stability of their livelihood
Promoting Agriculture, Health and Alternative Livelihoods (PAHAL)  |  Nepal  |  Number of people using climate information or implementing risk-reducing actions to improve resilience to climate change as supported by USG assistance
Promoting Agriculture, Health and Alternative Livelihoods (PAHAL)  |  Nepal  |  Number of communities verified as “open defecation free” as a result of USG assistance
Promoting Agriculture, Health and Alternative Livelihoods (PAHAL)  |  Nepal  |  Number of people gaining access to a basic sanitation service as a result of USG assistance
Promoting Agriculture, Health and Alternative Livelihoods (PAHAL)  |  Nepal  |  Number of people gaining access to a basic drinking water services as a result of USG assistance
Promoting Agriculture, Health and Alternative Livelihoods (PAHAL)  |  Nepal  |  Percentage of men, women, boys and girls who know at least 3 out of 5 critical times to wash hands
Promoting Agriculture, Health and Alternative Livelihoods (PAHAL)  |  Nepal  |  Average cereal crop production in kgs for personal consumption per participant HH
Promoting Agriculture, Health and Alternative Livelihoods (PAHAL)  |  Nepal  |  Number of hectares of land under improved technologies or management practices as a result of USG assistance
Promoting Agriculture, Health and Alternative Livelihoods (PAHAL)  |  Nepal  |  Number of communities with disaster early warning and response (EWR) systems working effectively
Promoting Agriculture, Health and Alternative Livelihoods (PAHAL)  |  Nepal  |  Percentage of households accessing key government and community services
Promoting Agriculture, Health and Alternative Livelihoods (PAHAL)  |  Nepal  |  Average rating of government's ability to be responsive to citizen's needs (including transparency, inclusivity, effectiveness, etc.), as measured on citizen scorecard (on a range of 1 - 5)
```

**Comment by KennyMonster** [comment]
The indicator form on open, will now set the target frequency to nothing if it's set, but not periodic targets exist. This should help old indicators in this funky state get back into shape by avoiding the case above where LoP only was selected in the target frequency, but the form was missing (because a PT didn't exist). This change was made in 3bd634f314f90028d1d154e5fee37e56e45cefc0

**Comment by jennyhavah** [comment]
@KennyMonster I'm experiencing some unexpected behaviors when I edit existing Event target values. As soon as I start typing in one of the value fields, I get this error message:

![image](https://user-images.githubusercontent.com/33670923/59534290-b429df80-8ea2-11e9-8f3b-0fbcd8d0af38.png)

I'd also like to remove the second sentence -- I think it confuses matters now that we have new conditions around allowing periodic targets to be zero -- like, they can't put zero placeholders for all their events, etc.

**Comment by jennyhavah** [comment]
@KennyMonster Small UI detail: When I select a target frequency, I get a flash of lightning. It's similar to what I describe in #1665 except I can't see anything opening and closing, just a general "blinky" effect.

If it's easy to fix, I'd appreciate it.

**Comment by jennyhavah** [comment]
@KennyMonster In general, the table is supper aggro about prompting me for values. I just typed one value in and tabbed to the next, and I see this.

![image](https://user-images.githubusercontent.com/33670923/59535729-89da2100-8ea6-11e9-9013-be6c2890acd1.png)

**Comment by KennyMonster** [comment]
> @KennyMonster Small UI detail: When I select a target frequency, I get a flash of lightning. It's similar to what I describe in #1665 except I can't see anything opening and closing, just a general "discotheque" effect.

I believe this is caused by the "loading" overlay flashing by. If you set the network to "slow 3g" in the chrome dev tools you can see it more thoroughly. Getting rid of the overlay in this case would leave the form clickable which is no ideal while loading. In theory this should be less of an issue when actual network latency is introduced.

**Comment by KennyMonster** [comment]
@jennyhavah I made the events targets a little less aggro by only checking validation on blur (when the focus leaves the input), but they are still a bit aggressive. The only other thing I can think of doing is checking validation on form submit only which seems to work ok when testing it locally. The downside is the validation messages do not go away on blur, which is something that would happen if validation checking remains attached to that event.

**Comment by jennyhavah** [comment]
@KennyMonster I'm going to start a new ticket to make further refinements to address overly aggro validation. Everything else in the ticket checks out.
