### ISSUE TITLE
Establish a new MEL Admin role that can only access Admin Lite

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2321]
Note: This issue is related to a couple of other Poblano issues -- cited in the acceptance criteria. It might make sense to do them together in a batch.

# Issue

We need to give additional MEL team members admin access to Admin Lite, but right now, Super Admin access _also_ grants access to the full Django admin. This introduces a higher level of risk than we're comfortable with.

# Acceptance criteria

- [ ] 1. There is a MEL Admin role that has all the same permissions as the Super Admin, but does NOT have access to the Django Admin. In other words, they are unable to login to Django Admin using their Mercy Corps credentials.

- [ ] 2. The MEL Admin is a Basic Admin in every country. (This is a big reason we need this role -- so that Super Admins don't have to grant MEL team members Basic Admin rights to each country, one by one.) Related to: Issue #1404.

- [ ] 3. The MEL Admin has High access to every program in every country. Also related to ticket #1404.

- [ ] 4. The MEL Admin role is picked up by the Admin Yes/No filter. Related issue: #1595 -- Filter currently only picks up Super Admins, not Basic Admins.

![image](https://user-images.githubusercontent.com/33670923/79788539-a8e2e400-82fd-11ea-9bbd-4e0bd99082ab.png)

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by mariebakke** [comment]
> Re: Open question: Do we want Basic Admins to have this capability?

Actually, this is not a bad idea. I know several Country Admins that pre-load programs into TolaData before they get entered into GAIT, so then they would need to go back to TolaData and edit the GAIT ID at a later point, once the program was funded and entered into GAIT.

**Comment by mariebakke** [comment]
Common tasks that I perform in Django are:
- Fixing users (related to #2329)
- Editing GAIT IDs 
- Deleting fake or test Programs or Organizations (often accidentally entered)
- Adding Countries (although, I just learned we can do this in Lite, so this is moot)
- Add or edit (never delete) lists: Data Collection Frequencies, Indicator Types, Reporting Frequencies, Sectors, and Profile Types

**Comment by jennyhavah** [comment]
> Fixing users (related to #2329)

I'm assuming 2329 takes care of this -- let us know if not.

> Editing GAIT IDs

Added criteria to this ticket.

> Add or edit (never delete) lists: Data Collection Frequencies, Indicator Types, Reporting Frequencies, Sectors, and Profile Types

@mariebakke Even if we leave out deletion, these types of additions and edits are systemic and profound in that they affect choices for all users. I think it's appropriate that only Super Admins be able to do these things, and would be nervous about broadening access. Something else to consider is that replicating all of these list management capabilities in Admin Lite would involve a significant amount of design and development effort.

So, my recommendation is that we continue limiting list management to Super Admins, and that you retain the Super Admin role even after we introduce a more limited MEL Admin role. 

> Deleting fake or test Programs or Organizations (often accidentally entered)

This functionality was purposely left out of Admin Lite, with the reasoning that it would be a rare event, and that very few people should be able to permanently delete an Organization or Program -- as opposed to making it Inactive, which Basic and Super Admin can do today. However, we didn't anticipate a large number of fake or test programs. 

@mariebakke Do you envision MEL Admins needing to do this on a fairly regular basis? If it would be a relatively rare event, then I wonder if it would be better to continue limiting this capability to Super Admins.

**Comment by mariebakke** [comment]
> @mariebakke Do you envision MEL Admins needing to do this on a fairly regular basis? If it would be a relatively rare event, then I wonder if it would be better to continue limiting this capability to Super Admins.

Actually, I have another case today, where a Country Admin added a "test" program to Production to which I will now have to go back and delete.

**Comment by mariebakke** [comment]
> So, my recommendation is that we continue limiting list management to Super Admins, and that you retain the Super Admin role even after we introduce a more limited MEL Admin role.

I am good with this.

**Comment by jennyhavah** [comment]
> @mariebakke Do you envision MEL Admins needing to do this on a fairly regular basis? If it would be a relatively rare event, then I wonder if it would be better to continue limiting this capability to Super Admins.

> > Actually, I have another case today, where a Country Admin added a "test" program to Production to which I will now have to go back and delete.

@mariebakke So just to clarify: Is deleting programs and organizations something you would like MEL Admins to be able to do, or would you prefer to limit it to Super Admins like yourself?

If we want MEL Admins to be able to perform these types of deletions, then I would file a separate ticket to add that capability to Admin Lite.

**Comment by jennyhavah** [comment]
5/7/2020 Confirmed that I'll create a separate ticket to add these deletion capabilities to Admin Lite. So, the scope of this ticket is set and ready for estimation.
