### ISSUE TITLE
Clean up css involved in Indicator Performance Tracking Table (IPTT)

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#299]
This follows work on related tickets #120, #121 & possibly others. Will likely involve some CSS refactoring tracked separately on #300

**Comment by axoplasm** [comment]
Subtasks:
- [ ] Navbar is constrained to inner container which looks weird on this page
- [ ] Filter toggle needs a more explicit icon & label
- [ ] Padding around filter toggle
- [ ] Filter expand/collapse function pushes table off the page
- [ ] Table breaks viewport
- [ ] Filter panel indistinguishable from header
- [ ] Target table popup doesn't work in Safari/Mac

**Comment by axoplasm** [comment]
There is related work in #298 & #239
