### ISSUE TITLE
IPTT filter panel: Updating time period and start/end options in the background

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#358]
# Revisit this one, maybe don't do it.

**Affects:** Both versions of the IPTT report.

# Target vs Actuals IPTT
- [x] 1. When I change to a different _program_, I want my target period and start/end options to refresh immediately (in the background) so that I don't have to click _Apply_ to see all of my available options.
- [x] 1.1. I should only see target period options for which there is at least one indicator with targets of that type. (Test for regressions.)
- [x] 1.2. If I previously had _Most recent X_ selected, the system should ideally preserve that selection. (Test for regressions on #347.) 
- [x] 1.3. If the new program doesn't have any indicators that share the previously selected target frequency, it reverts to _Show all_ and the first option in the target frequency menu. (Again, checking for regressions.)
- [x] 2. _Without changing the program_, if I select a different _target period_, I want my start/end period options to refresh immediately in the background.
- [x] 2.1. If I previously had _Most recent X_ selected, the system should ideally preserve that selection. (Test for regressions on #347.)

# Recent Progress IPTT
- [x] 1. When I change to a different _program_, I want my time period and start/end options to refresh immediately (in the background) so that I don't have to click _Apply_ to see all of my available options.
- [x] 1.1. If I previously had _Most recent X_ selected, the system should ideally preserve that selection. (Test for regressions on #347.)
- [x] 2. _Without changing the program_, if I select a different _time period_, I want my start/end period options to refresh immediately in the background.
- [x] 2.1. If I previously had _Most recent X_ selected, the system should ideally preserve that selection. (Test for regressions on #347.)

**Comment by jennyhavah** [comment]
This is all done! Closing.
