### ISSUE TITLE
Internationalization, Localization & Translation (EPIC)

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#498]

**Comment by axoplasm** [comment]
Per commit a6ced44:

We are prioritizing translating strings in some, but not all, of the workflow app. Specifically, we are targeting templates that affect display of:

* Programs
* Tola Users
* Sites
* Documents

(We are also prioritizing display of Reports and Indicators, but these are handled in the Indicators app and should already be marked)

### This changes the plan at little:

1. [ ] Revert `templates/workflow`
2. [ ] Finish localization for testing next week (of 2018-08-20)
3. [ ] Mark strings for translation as described above.
4. [ ] **IMPORTANT** Add dummy (e.g. `ZZZ`) text to `.po` files for marked but untranslated strings.
5. [ ] Test localization *and* translation. Strings that appear in the UI in English are known to be **unmarked**. Strings that appear as `ZZZ` are known to be **marked but untranslated**.
6. [ ] Send tested .po files for translation
7. [ ] Test only translation **which will be _PERFECT_**

**Comment by axoplasm** [comment]
*fuzzy* translations are proving problematic. I stumbled into this with embedded strings (aka via `{% blocktrans %}`). msgids tagged fuzzy are not getting compiled into .mo files (?) See https://stackoverflow.com/questions/1377372/django-fuzzy-string-translation-not-showing-up#1377396 for a clue. See also commits ba138fa and f9952e8

**Comment by axoplasm** [comment]
Update! With a hint from Daniel, I was able to narrow the problem down to the `fuzzy` tag thus vindicating @sanjuroj's theory. I have several micro-commits stepping through my experiments:

* eb3c8d9 reverted .po and .mo files to the last state we received them from the translators (i.e. with many missing msgids)
* 6c5637f reran makemessages, excluding the venv directory
* 6d20231 recompiled .mo files, which reproduced the error state we had before I began hacking .po files last week
* (we can ignore 95d0afa, where I was experimenting with my use of `{% blocktrans %}`. This might be problematic (see https://docs.djangoproject.com/en/2.1/topics/i18n/translation/#blocktrans-template-tag) but is not germane to this testing)
* (we can also ignore 03fefdb and ac84876, where I was fiddling with a single string)
* ba3657a was the Eureka commit! Removing `#, fuzzy` from the .po by brute force “fixed” the error.
* 18f4e01 is __very important__ but ultimately not related to this test
* __Finally the next three commits (ending at b4a215b) brings us to a state where we can test translations as I outlined above.__ Our dummy text is "XXX"

**Comment by axoplasm** [comment]
So here’s what will need to happen with translations:

__UNO:__ Finish visual testing to find `XXX` strings, as outlined above. There are a lot! The pages will look like this:

![screen shot 2018-08-31 at 11 52 20 am](https://user-images.githubusercontent.com/169060/44931540-d806a500-ad16-11e8-8815-42b49603f5e5.png)

    - Anywhere we see `XXX` we have a __tagged but not translated__ string.
    - Anywhere we see English we have an __untagged__ string (or text directly from the database

__DEUX__: There are about two dozen places where translators didn’t provide a placeholder for replacement strings. I’ve “fixed” this in one place, see 18f4e01. (Note however that I don’t speak French so this is almost certainly wrong.) When we send the updated .po files off to be translated, __they need to provide replacement strings__ in the msgstr per the syntax in this commit.
