### ISSUE TITLE
EPIC: Home page: Site map and country filter

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#544]
**Description:** We want to include today's home page site map on our new home page. Layout-wise, it'll be placed something like this:

![image](https://user-images.githubusercontent.com/33670923/48170626-2dc67300-e2ad-11e8-8556-d0c09d105549.png)

# Acceptance criteria

## Layout and basic functionality
- [x] 1. The site map appears on the page.
- [x] 2. Above the site map, I see the name of the country. 
     - **Note:** With Mangosteen, you will only be able to view one country at a time. We are no longer going to offer an "all countries" option. In the future, we may explore a custom portfolio option.
- [x] 3. The page displays all programs with Funded status that are associated with the current country.
     - [x] 3.1. If a program is associated with multiple countries, it shows up in the program list for any of the countries it belongs to.
- [x] 4. **Changing country**
     - [x] 4.1. If I only have permission to see my own country, then I do NOT see a country menu.
     - [x] 4.2. If I have access to more than one country, there is a "Change country" menu right next to the current country name. It only shows me the countries I have permission to see. 
- [x] 5. The first time I access the home page, I see <s>my own country</s> the first country in my “accessible countries” list, in alphanumeric order
- [x] 6. If I then select a different country, the system remembers it. So that if I navigate away from the home page and then click the Tola icon to get back home, I see the last country I selected.
     - [x] 6.1. <s>I think this should only last as long as the session. Next session, you see your own country. Let me know if you disagree.</s> This change will persist between sessions.

## Filtering by program 
_Note: This feature appears to be rather broken. We need to weigh the costs/risks of attempting to fix it for Mangosteen vs temporarily removing the feature and pulling it into a Ghost Pepper or Fruit Basket ticket._ 

_Note 2018-11-12: The Program filtering is not ready for release. Not sure what it filters on the homepage, and not clear that the data support it robustly._

- [ ] <s>1. There is a program menu above the site map -- maybe right-aligned with the map, in line with the Change country menu.</s>
- [x] 2. I only see programs associated with the currently selected country.
- [ ] <s>3. The program menu default is  "None selected". In other words, I see all programs in the country.</s>
- [ ] <s>4. If I select a program, The map only shows me sites associated with that program.</s>
     - [ ] <s>4.1. Both blue and orange type site pins appear. (One of the two colors represents a site with results associated with it. </s>
- [ ] <s>5. Open question: Should selecting a program change the metrics to the right of the map, or do we want it to stay at country level? My instinct is to keep it country level, because the program page is where we want people to go for program-level metrics. </s>

## Zooming and layers
- [x] 1. Zooming in and out works as expected
- [x] 2. Layers work as they do on production -- meaning this business:
![image](https://user-images.githubusercontent.com/33670923/43808746-498ebd0a-9a63-11e8-9253-deff836ced85.png)
- [x] 3. If it is a trivial change, let's make the two pin checkboxes more intuitive.
     - [x] 7.1. Project Sites --> Program sites
     - [x] 7.2. Indicator Data Sites --> Sites with data

**Comment by axoplasm** [comment]
@sanjuroj we will probably need to break this into several smaller tasks. I can work on the leaflet components but there's a lot of asynch JS & DB work that I can't do v efficiently

**Comment by axoplasm** [comment]
@jennyhavah This is feature complete as described in Criteria 5, 6, and 6.1 . This means selected country does not persist between sessions. It also means the edges I explored in #779 are not addressed.

**Comment by axoplasm** [comment]
See additional notes in #779 about implemented behavior for homepage country filter

**Comment by mariebakke** [comment]
PASS - 1. The site map appears on the page.
PASS - 2. Above the site map, I see the name of the country.
PASS - 2.1. You will only be able to view one country at a time.
PASS - 3. The page displays all programs with Funded status that are associated with the current country.
ERROR MESSAGE (see screen shot below) - 3.1. If a program is associated with multiple countries, it shows up in the program list for any of the countries it belongs to.
  4. Changing country
PASS - 4.1. If I only have permission to see my own country, then I do NOT see a country menu.
PASS - 4.2. If I have access to more than one country, there is a "Change country" menu right next to the current country name. It only shows me the countries I have permission to see.
PASS - 5. The first time I access the home page, I see the first country in my “accessible countries” list, in alphanumeric order
PASS - 6. If I then select a different country, the system remembers it. So that if I navigate away from the home page and then click the Tola icon to get back home, I see the last country I selected.
PASS - 6.1. This change will persist between sessions.

**Comment by mariebakke** [comment]
Result of testing 3.1. I am using QA Program - Marie, which is assigned to Tolaland and USA. When I clicked on the "change country" drop down menu on the Home Page, I got this error:

![screen shot 2018-11-28 at 4 50 10 pm](https://user-images.githubusercontent.com/45101655/49184570-bfb22080-f32d-11e8-89c6-716d61fd1bdc.png)

**Comment by axoplasm** [comment]
Whew I can't do anything about that. @sanjuroj can we provision more memory? Restart the server?

**Comment by mariebakke** [comment]
Okay, I just retested and...
PASS - 3.1. If a program is associated with multiple countries, it shows up in the program list for any of the countries it belongs to.

**Comment by mariebakke** [comment]
Filtering By Program
PASS - 2. I only see programs associated with the currently selected country.

**Comment by mariebakke** [comment]
Zooming and Layering:
PASS - 1. Zooming in and out works as expected
FAIL @axoplasm - 2. Layers work as they do on production -- meaning this business:
3. If it is a trivial change, let's make the two pin checkboxes more intuitive.
PASS - 7.1. Project Sites --> Program sites
CANNOT TEST - 7.2. Indicator Data Sites --> Sites with data

**Comment by mariebakke** [comment]
This is Production with Blue and Orange Pin Drops that delineate Sites With Data and Program Sites, respectively

![screen shot 2018-11-28 at 5 56 03 pm](https://user-images.githubusercontent.com/45101655/49187877-e9237a00-f336-11e8-9359-7cb88396f9e7.png)

**Comment by mariebakke** [comment]
@axoplasm : This is Demo. Blue Pin Drops are missing. Therefore, I cannot toggle Layers or test Indicator Data Site => Sites with Data. 

![screen shot 2018-11-28 at 5 57 49 pm](https://user-images.githubusercontent.com/45101655/49187966-225bea00-f337-11e8-82c5-54f9de1d177e.png)

**Comment by sanjuroj** [comment]
Hmmm, I wonder if the missing blue pins are a reversion of #96.

**Comment by mariebakke** [comment]
Zooming and Layering:
PASS - 1. Zooming in and out works as expected
PASS - 2. Layers work as they do on production.
3. If it is a trivial change, let's make the two pin checkboxes more intuitive.
FAIL - 7.1. Project Sites --> Program sites
FAIL - 7.2. Indicator Data Sites --> Sites with data

**Comment by mariebakke** [comment]
![screen shot 2018-11-30 at 11 30 19 am](https://user-images.githubusercontent.com/45101655/49301744-564c2200-f493-11e8-9ab6-54e6788ada32.png)

**Comment by mariebakke** [comment]
Also, please note that even though we have improved the labeling in the layers, the pop-outs/bubbles are still reflecting the old labeling.
![screen shot 2018-11-30 at 11 30 56 am](https://user-images.githubusercontent.com/45101655/49301827-7f6cb280-f493-11e8-8b9c-4a0acd5658c8.png)

**Comment by KennyMonster** [comment]
> FAIL - 7.1. Project Sites --> Program sites
> FAIL - 7.2. Indicator Data Sites --> Sites with data

The label change seen in the layers menu to "Sites with results" and "Sites without results" came out of a discussion yesterday w/ @jennyhavah. I can update the out-of-date labels in the pop-over bubbles for the map marker to match the layer menu labels if that works for everyone.

**Comment by KennyMonster** [comment]
I just realized none of the strings in the map overlay window or map marker popover are marked for translation. I'm assuming all of these need to be translated?

**Comment by jennyhavah** [comment]
@KennyMonster I think it's worth adding to our translation bug epic in Ghost Pepper, yes. Not urgent for Mangosteen, in my view, as it's been this way forever.
