### ISSUE TITLE
EPIC: Fruity program page

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#545]
This ticket is for reference purposes, gathering together all of the work related to the Fruity program page.

- [x] #548 Visual design refinement
- [x] #555 Scaffold
- [x] #558 Page title row and charts row
- [x] #543 Queries for program summary metrics
- [x] #559 Indicator list with results tables
- [x] #560 Highlight indicators with no targets
- [x] <s>#558 (?) Highlight reported results: not implemented, we only show indicators without reported results</s>
- [x] #561 Highlight indicators missing performance targets
- [x] #562 Highlight reported results missing evidence
- [x] #574 Program details sidebar
- [x] #589 Display and delete pinned reports
- [x] #588 IPTT report: Pin this IPTT
- [x] #564 Top nav: Program menu

![mangosteen-program-2](https://user-images.githubusercontent.com/33670923/48165037-32812c00-e299-11e8-8d9a-c43fe713ba8e.png)

**Comment by sanjuroj** [comment]
@jennyhavah The current indicator list page, which is the page most similar to this one, has filters for indicator and type.  Are we still providing those?

**Comment by jennyhavah** [comment]
@sanjuroj Good question. I can see those filters being helpful for complex programs that have over 100 indicators. I realize I neglected to include them in the program page mockup, which I just refreshed on this ticket with the most recent design. @axoplasm can you please incorporate these two filters into the design?
