### ISSUE TITLE
EPIC: Home page: Program blob

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#551]
Every program has a blob of content and metrics, like so:

![image](https://user-images.githubusercontent.com/33670923/48167564-f4880600-e2a0-11e8-8ba9-0ab8b6851cc5.png)

The blob includes:

- [x] 1. Program name
- [x] 1.1. Program name links to the program page
- [x] 2. Program period complete graphic -- see #549 
- [x] 2.1. Graphic links to the program period modal (formerly called the "reporting period" modal)
- [x] 3. Indicators on track
- [ ] 3.1. <s>Includes a link to the program page filtered on those indicators that are not on track (#561)</s>
- [x] 4. Indicators with targets
- [ ] 4.1. <s>Includes a link to the program page filtered on those indicators that do not have targets (#560 )</s>
- [x] 5. Indicators with results
- [ ] 5.1. <s>Includes a link to the program page filtered on those indicators that do have results (#562)</s>
- [x] 6. Results with evidence
- [ ] 6.1. <s>Includes a link to the program page filtered on those indicators that have results with no evidence (#563)</s>

- [x] Keep in mind that we will need empty state variations for the program blob, captured in #552.

## Housekeeping
- [ ] Unit test/s written
- [ ] i18n tags included wherever applicable

**Comment by axoplasm** [comment]
Except for indicator filters, there is significant overlap with #558 & gauge-related items.

**Comment by jennyhavah** [comment]
All elements are in place.
