### ISSUE TITLE
EPIC: Program page: Page title row and charts row

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#558]
This ticket covers the page title row and charts row of the scaffold (#556)

![image](https://user-images.githubusercontent.com/33670923/48167502-b854a580-e2a0-11e8-9bc5-834627d117d7.png)

## Page title row
- [x] 1. Page title = Program name
- [x] 2. Reporting period chart (#549) with a link to the program period modal

## Charts row 
**Note:** Chart queries are tackled in #543. Chart generation is tackled in #550 and #577
- [x] 1. Indicators on track (#577)
- [x] 1.1. Link to highlight indicators more than 15% _above_ the target (#561 )
- [x] 1.1. Link to highlight indicators more than 15% _below_ the target (also #561)
- [x] 1.1. LInk to highlight indicators on track (#561)
- [x] 2. Indicators with targets 
- [x] 2.1. Link to highlight indicators that have no targets (#560)
- [x] 3. Indicators with results
- [x] 3.1.Link to highlight indicators with no results (#562)
- [x] 4. Results with evidence
- [x] 4.1. Link to highlight results missing evidence (#563)

## Housekeeping
- [ ] Unit test/s written
- [ ] i18n tags included wherever applicable

**Comment by axoplasm** [comment]
I think either @Sanjuro or myself (or both) could do this. It might be EPIC

**Comment by jennyhavah** [comment]
Some usability/design feedback for @axoplasm regarding the program page graphs...  Because I am able to click individual links on the "Indicators on track" chart, I find myself repeatedly trying to click on the individual metrics on the other charts as well -- the "x% no targets" or the "91% have evidence", etc.

I do NOT think we should change how any of the graphs function, in terms of what you can/can't filter. But I had an idea for visually differentiating "On track has several different filters" from "This whole thing is a filter". What if, for the three charts EXCEPT for on track, the entire background highlights in yellow, on-hover and on-click, to suggest "this whole thing is a single clickable area? Then once you've clicked, it settles into the yellow outline. We would NOT do that with the Indicators on track one, to communicate that it's NOT one big clickable target.

This does not block the ticket being done -- just wanted to share the idea.

**Comment by jennyhavah** [comment]
All components are in place.
