### ISSUE TITLE
Program page: Program details sidebar

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#574]
The **Program details** sidebar gathers together documents, sites, and pinned reports associated with a program.

![image](https://user-images.githubusercontent.com/33670923/44566956-1acbea00-a725-11e8-99b1-f25f5b0979d4.png)

# Acceptance criteria

## General
- [x] 1. The sidebar has the header "Program details"
- [x] 2. Under the header is a link to the program's indicator plan

There are three sub-sections: Documents; Sites; and Pinned reports

## Documents
- [x] 1. _View program documents_ link takes you to the /workflow/documentation_list/0/0/ page filtered in the following ways:
- [x] 1. Only documents associated with the program
- [x] 2. _Add document_ button takes you to /workflow/documentation_add _with the program pre-selected_

## Sites
- [x] 1. _View program sites_ link takes you to /workflow/siteprofile_list/XXX/0/?user_list=XX already filtered to the current program
- [x] 2. _Add site_ button takes you to /workflow/siteprofile_add ~~_with the program pre-selected_~~

## Pinned reports
See ticket #589 **Display and delete pinned reports.**

**Comment by axoplasm** [comment]
This may be an EPIC, it has a lot of parts.

**Comment by KennyMonster** [comment]
@jennyhavah 

> 2. Add site button takes you to /workflow/siteprofile_add with the program pre-selected

The site add form doesn't have a program form element or link at the DB level, so the link for now just goes to the new sites form as if clicked form the sites list page.

**Comment by jennyhavah** [comment]
Got it. Crossed out that part.

**Comment by axoplasm** [comment]
Fixed in 31ed977

![image](https://user-images.githubusercontent.com/169060/49182119-363f2600-f30e-11e8-9540-4c9e3970537e.png)

**Comment by esinn** [comment]
Not sure if this is directly related to this ticket or not, but when I click on view program documents and it takes me to the document page, right now it doesn't specify which program I'm viewing (see program name dropdown - just says program). Ideally, it'd be nice for it show the name of the specific program you're viewing. Same goes for when I click on the View program sites from the program page, doesn't show me which program I'm viewing.
![image](https://user-images.githubusercontent.com/13574772/49185788-b027dd00-f317-11e8-8ece-e9624141e126.png)
![image](https://user-images.githubusercontent.com/13574772/49185859-dd748b00-f317-11e8-88ec-389c3129146a.png)

**Comment by axoplasm** [comment]
@esinn I would say this is separate issue, as it's not on the Program page itself. See #858. @jennyhavah is this otherwise complete?

**Comment by esinn** [comment]
Ok, I wasn't sure. Then yes @axoplasm it's complete. Moving to done. 👍

**Comment by jennyhavah** [comment]
If everything else looks good to Emily, then I agree it's done. I'll file a new ticket for the program documents issue.

**Comment by jennyhavah** [comment]
Actually, I take that back. That was a requirement of this ticket, so I moved it to Failed.

I may have confused things by crossing out the wrong item in the original ticket -- document instead of site.

@KennyMonster I know we can't link to the Add site page with the program pre-selected, but any reason we can't do this with documents? Documents are definitely associated with programs -- it's one of the fields in the form.

**Comment by jennyhavah** [comment]
Okay, I completely misunderstood Emily's comment and thought it was referring to a failure to filter the documents. I un-Failed the ticket and moved it back to Done.

Paul's on it, as a separate ticket!
