### ISSUE TITLE
Translation bugs

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#669]
For all of the bugs associated with this epic, we need to:
- [ ] Add translation tags
- [ ] Send translation file to translation firm
- [ ] Upload the refreshed translation file
- [ ] Generate the binary files

**Translation bugs:**
~~#598 Indicator Target Period names not translated~~
- [x] #602 Add a site tab titles
- [x] #603 Add a site > Profile tab
- [x] #604 Add a site > Location tab
- [x] #605 Add a site > Demographic info tab
- [x] #668 Profile form
~~#736 "Indicator Performance Tracking Table" not translated~~
~~#896 Indicator setup form > Performance tab~~ <-- DB field, moved to Satsuma overflow
~~#897 IPTT filter panel~~ <-- DB values, moved to Satsuma overflow

**Comment by KennyMonster** [comment]
All of these references tickets are completed, or they are DB values.

**Comment by jennyhavah** [comment]
Thanks, @KennyMonster -- closing the ticket.
