### ISSUE TITLE
EPIC: Record form and database object

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#811]
This epic aggregates tickets related to the Document form.

# Tickets
- [ ] #809 Record form: UI updates to page title, form fields, and links
- [ ] #822 Record form: Validate record name and file path to prevent duplication of records
- [ ] #862 Record form: Restrict changes to Program
- [ ] #842 Record form: Display linked results on the record form
- [ ] #810 Record form: Add explanatory messaging
- [ ] #841 Record form: Move "delete record" function to Record form
- [ ] #831 Delete a record: Replace full page confirmation with Pnotify dialogue
- [ ] #818 Record page: Replace Project and Program menus with newer select widget

![image](https://user-images.githubusercontent.com/33670923/48730436-31cc8c00-ebef-11e8-8f4d-74235611cf31.png)

**Comment by jennyhavah** [comment]
Since documents will only be linked to Projects going forward, and we are no longer making improvements that only benefit Projects, I'm closing this Epic ticket.
