### ISSUE TITLE
EPIC: Browse documents

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#812]
This epic aggregates tickets related to the Browse > Documents page.

## Tickets
- [x] #150 Browse documents: Layout, labeling, and link modifications
- [x] #805 Browse documents: Change default sort and enable manual sorting
- [x] #892 Browse documents: Filter by indicator
- [x] #645 Browse documents: Add Find a document select widget
- [x] #834 Browse documents: Replace Program menu with newer select widget

**Original page**
![image](https://user-images.githubusercontent.com/33670923/48793354-90574000-ecab-11e8-986b-1979eea9e4a1.png)

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Media Verifying: 
![screen shot 2019-02-13 at 11 57 43 am](https://user-images.githubusercontent.com/23220180/52739823-985f0d00-2f86-11e9-9127-1eeb4e4ae56d.png)
