### ISSUE TITLE
EPIC: Result form

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#813]
This epic aggregates tickets related to the Result form.

# Tickets
- [x] #808 Result form: UI updates (reorganization, relabeling, styling)
- [x] #893 Result form: Restrict the entry of results with a result date after today
- [x] #816 Result form: Easily validate / access file or folder path
- [x] #827 Results form: Add explanatory messaging
- [x] #830 Delete a result: Replace full page confirmation with Pnotify dialogue

**Original page**
![image](https://user-images.githubusercontent.com/33670923/48793436-c98fb000-ecab-11e8-9bd9-3089f3b57820.png)

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] All linked tickets to this epic have been verified, and met Acceptance Criteria.
